/**
 * The concept registry.
 *
 * Every concept carries the level-3 hint text, the rival spellings used at
 * hint level 5, and a review pool. The pool does double duty: cumulative
 * review in later exercises (spec §12) and the remediation questions the
 * engine injects when a child gets the concept wrong (spec §2).
 *
 * A pool must be deep enough that a repeated mistake always draws a word the
 * child has not just seen — that is what makes "prove it independently" real.
 */
import type { Concept, ConceptId } from '../spelling/types'
import { aud, build, cloze, letters, mistake, pat, sort, syl } from './build'

const CONCEPT_LIST: Concept[] = [
  {
    id: 'syllables',
    label: 'Splitting words into beats',
    patternReminder: 'Clap the word. Each clap is a beat, and you spell one beat at a time.',
    introducedIn: 1,
    reviewPool: [
      syl('syl-r1', 'syllables', 'basket'),
      syl('syl-r2', 'syllables', 'jumper'),
      syl('syl-r3', 'syllables', 'picnic'),
      syl('syl-r4', 'syllables', 'magnet'),
      syl('syl-r5', 'syllables', 'tennis'),
      syl('syl-r6', 'syllables', 'garden'),
      syl('syl-r7', 'syllables', 'remember', { difficulty: 2 }),
      syl('syl-r8', 'syllables', 'important', { difficulty: 2 }),
      syl('syl-r9', 'syllables', 'yesterday', { difficulty: 2 }),
      syl('syl-r10', 'syllables', 'telescope', { difficulty: 3 }),
      aud('syl-r11', 'syllables', 'afternoon', { difficulty: 2 }),
      aud('syl-r12', 'syllables', 'lemonade', { difficulty: 2 }),
    ],
  },
  {
    id: 'ee-sound',
    label: 'The /ee/ sound',
    patternReminder:
      'The /ee/ sound has a few spellings. "ee" and "ea" usually sit inside a word, and "y" or "ey" usually come at the end.',
    alternatives: ['ee', 'ea', 'y', 'ey'],
    introducedIn: 2,
    reviewPool: [
      aud('ee-r1', 'ee-sound', 'sheep'),
      aud('ee-r2', 'ee-sound', 'dream'),
      aud('ee-r3', 'ee-sound', 'queen'),
      aud('ee-r4', 'ee-sound', 'treat'),
      aud('ee-r5', 'ee-sound', 'sunny'),
      aud('ee-r6', 'ee-sound', 'donkey'),
      pat('ee-r7', 'ee-sound', 'green', { choices: ['ee', 'ea'] }),
      pat('ee-r8', 'ee-sound', 'clean', { choices: ['ea', 'ee'] }),
      pat('ee-r9', 'ee-sound', 'twenty', { choices: ['y', 'ey'] }),
      letters('ee-r10', 'ee-sound', 'between', { difficulty: 2 }),
      letters('ee-r11', 'ee-sound', 'teacher', { difficulty: 2 }),
      cloze('ee-r12', 'ee-sound', 'We go swimming once a ___.', 'week', { difficulty: 2 }),
      aud('ee-r13', 'ee-sound', 'cheese'),
      aud('ee-r14', 'ee-sound', 'valley', { difficulty: 2 }),
    ],
  },
  {
    id: 'oa-sound',
    label: 'The /oa/ sound',
    patternReminder:
      'The /oa/ sound has several spellings. "oa" usually sits inside a word, while "ow", "oe" and o_e often come near the end.',
    alternatives: ['oa', 'ow', 'oe', 'o'],
    introducedIn: 3,
    reviewPool: [
      aud('oa-r1', 'oa-sound', 'goat'),
      aud('oa-r2', 'oa-sound', 'toast'),
      aud('oa-r3', 'oa-sound', 'yellow'),
      aud('oa-r4', 'oa-sound', 'elbow'),
      aud('oa-r5', 'oa-sound', 'stone'),
      aud('oa-r6', 'oa-sound', 'rope'),
      pat('oa-r7', 'oa-sound', 'road', { choices: ['oa', 'ow'] }),
      pat('oa-r8', 'oa-sound', 'snow', { choices: ['ow', 'oa'] }),
      letters('oa-r9', 'oa-sound', 'float', { difficulty: 2 }),
      letters('oa-r10', 'oa-sound', 'pillow', { difficulty: 2 }),
      aud('oa-r11', 'oa-sound', 'throat', { difficulty: 2 }),
      aud('oa-r12', 'oa-sound', 'tiptoe', { difficulty: 2 }),
      cloze('oa-r13', 'oa-sound', 'There is a ___ in my sock.', 'hole', { difficulty: 2 }),
      aud('oa-r14', 'oa-sound', 'smoke'),
    ],
  },
  {
    id: 'plural-s-es',
    label: 'Plurals with -s and -es',
    patternReminder:
      'Most words just add "s". If the word already ends in a hissing or buzzing sound — s, sh, ch, x or z — it needs "es".',
    alternatives: ['s', 'es'],
    introducedIn: 4,
    reviewPool: [
      aud('pl-r1', 'plural-s-es', 'foxes'),
      aud('pl-r2', 'plural-s-es', 'dishes'),
      aud('pl-r3', 'plural-s-es', 'benches'),
      aud('pl-r4', 'plural-s-es', 'glasses'),
      aud('pl-r5', 'plural-s-es', 'books'),
      aud('pl-r6', 'plural-s-es', 'chairs'),
      cloze('pl-r7', 'plural-s-es', 'We waited at the stop for two ___.', 'buses', { difficulty: 2 }),
      cloze('pl-r8', 'plural-s-es', 'There are three ___ on the shelf.', 'boxes', { difficulty: 2 }),
      sort('pl-r9', 'plural-s-es', { '+s': ['trees', 'hands'], '+es': ['wishes', 'matches'] }),
      mistake('pl-r10', 'plural-s-es', 'We washed all the dishs after dinner.', 'dishs', 'dishes', { difficulty: 2 }),
      aud('pl-r11', 'plural-s-es', 'churches', { difficulty: 2 }),
      aud('pl-r12', 'plural-s-es', 'taxes', { difficulty: 3 }),
    ],
  },
  {
    id: 'plural-y-ies',
    label: 'Words ending in y',
    patternReminder:
      'If a consonant comes before the "y", change the y to i and add "es". If a vowel comes before the y, just add "s".',
    alternatives: ['ies', 'ys'],
    introducedIn: 5,
    reviewPool: [
      aud('yi-r1', 'plural-y-ies', 'cherries'),
      aud('yi-r2', 'plural-y-ies', 'parties'),
      aud('yi-r3', 'plural-y-ies', 'ladies'),
      aud('yi-r4', 'plural-y-ies', 'puppies'),
      aud('yi-r5', 'plural-y-ies', 'keys'),
      aud('yi-r6', 'plural-y-ies', 'monkeys'),
      cloze('yi-r7', 'plural-y-ies', 'The two ___ were fast asleep.', 'babies', { difficulty: 2 }),
      cloze('yi-r8', 'plural-y-ies', 'We visited three different ___.', 'countries', { difficulty: 3 }),
      sort('yi-r9', 'plural-y-ies', { 'y becomes ies': ['stories', 'pennies'], 'just add s': ['days', 'toys'] }),
      mistake('yi-r10', 'plural-y-ies', 'The butterflys landed on the flowers.', 'butterflys', 'butterflies', {
        difficulty: 2,
      }),
      aud('yi-r11', 'plural-y-ies', 'armies', { difficulty: 2 }),
      aud('yi-r12', 'plural-y-ies', 'valleys', { difficulty: 2 }),
    ],
  },
  {
    id: 'compound-words',
    label: 'Compound words',
    patternReminder:
      'Find the two smaller words hiding inside. Each one usually keeps its own spelling exactly as it was.',
    maskFrom: 'lastPart',
    introducedIn: 6,
    reviewPool: [
      aud('cw-r1', 'compound-words', 'toothbrush'),
      aud('cw-r2', 'compound-words', 'playground'),
      aud('cw-r3', 'compound-words', 'sunflower'),
      aud('cw-r4', 'compound-words', 'snowman'),
      aud('cw-r5', 'compound-words', 'notebook'),
      aud('cw-r6', 'compound-words', 'weekend'),
      build('cw-r7', 'compound-words', ['camp', 'fire'], 'campfire'),
      build('cw-r8', 'compound-words', ['door', 'bell'], 'doorbell'),
      build('cw-r9', 'compound-words', ['pop', 'corn'], 'popcorn'),
      cloze('cw-r10', 'compound-words', 'I finished my ___ before dinner.', 'homework', { difficulty: 2 }),
      aud('cw-r11', 'compound-words', 'blackboard', { difficulty: 2 }),
      aud('cw-r12', 'compound-words', 'skyscraper', { difficulty: 3 }),
    ],
  },
  {
    id: 'consonant-doubling',
    label: 'Doubling the last consonant',
    patternReminder:
      'Short word, one vowel then one consonant, and the ending starts with a vowel? Double that last consonant.',
    alternatives: ['nn', 'n', 'pp', 'p', 'tt', 't'],
    introducedIn: 7,
    reviewPool: [
      aud('cd-r1', 'consonant-doubling', 'swimming'),
      aud('cd-r2', 'consonant-doubling', 'shopping'),
      aud('cd-r3', 'consonant-doubling', 'clapping'),
      aud('cd-r4', 'consonant-doubling', 'dropped'),
      aud('cd-r5', 'consonant-doubling', 'jogging'),
      aud('cd-r6', 'consonant-doubling', 'winning'),
      build('cd-r7', 'consonant-doubling', ['hug', '+ing'], 'hugging'),
      build('cd-r8', 'consonant-doubling', ['chat', '+ing'], 'chatting'),
      cloze('cd-r9', 'consonant-doubling', 'She was ___ across the puddles.', 'skipping', { difficulty: 2 }),
      mistake('cd-r10', 'consonant-doubling', 'The bus stoped at the corner.', 'stoped', 'stopped'),
      aud('cd-r11', 'consonant-doubling', 'grabbing', { difficulty: 2 }),
      aud('cd-r12', 'consonant-doubling', 'tripping', { difficulty: 2 }),
    ],
  },
  {
    id: 'drop-silent-e',
    label: 'Dropping the silent e',
    patternReminder:
      'If the word ends in a silent e and the ending starts with a vowel, the e is not needed any more. Drop it.',
    introducedIn: 8,
    reviewPool: [
      aud('de-r1', 'drop-silent-e', 'baking'),
      aud('de-r2', 'drop-silent-e', 'riding'),
      aud('de-r3', 'drop-silent-e', 'smiling'),
      aud('de-r4', 'drop-silent-e', 'moving'),
      aud('de-r5', 'drop-silent-e', 'closing'),
      aud('de-r6', 'drop-silent-e', 'shining'),
      build('de-r7', 'drop-silent-e', ['dance', '+ing'], 'dancing'),
      build('de-r8', 'drop-silent-e', ['drive', '+ing'], 'driving'),
      cloze('de-r9', 'drop-silent-e', 'He is ___ a letter to his cousin.', 'writing', { difficulty: 2 }),
      mistake('de-r10', 'drop-silent-e', 'We are makeing a cake.', 'makeing', 'making'),
      aud('de-r11', 'drop-silent-e', 'saving', { difficulty: 2 }),
      aud('de-r12', 'drop-silent-e', 'using', { difficulty: 2 }),
    ],
  },
  {
    id: 'ed-endings',
    label: 'The -ed ending',
    patternReminder:
      'Past-tense words almost always end in "ed", even when it sounds like /t/ or /d/ or adds a whole beat.',
    alternatives: ['ed', 't', 'd'],
    maskFrom: 'lastPart',
    introducedIn: 9,
    reviewPool: [
      aud('ed-r1', 'ed-endings', 'walked'),
      aud('ed-r2', 'ed-endings', 'landed'),
      aud('ed-r3', 'ed-endings', 'kicked'),
      aud('ed-r4', 'ed-endings', 'shouted'),
      aud('ed-r5', 'ed-endings', 'cleaned'),
      aud('ed-r6', 'ed-endings', 'pointed'),
      sort('ed-r7', 'ed-endings', {
        'sounds like /t/': ['jumped', 'walked'],
        'sounds like /d/': ['played', 'cleaned'],
        'adds a beat': ['wanted', 'landed'],
      }),
      cloze('ed-r8', 'ed-endings', 'We ___ for the bus in the rain.', 'waited', { difficulty: 2 }),
      mistake('ed-r9', 'ed-endings', 'She jumpt over the puddle.', 'jumpt', 'jumped'),
      aud('ed-r10', 'ed-endings', 'painted', { difficulty: 2 }),
      aud('ed-r11', 'ed-endings', 'helped', { difficulty: 2 }),
      build('ed-r12', 'ed-endings', ['want', '+ed'], 'wanted'),
    ],
  },
  {
    id: 'plural-sounds',
    label: 'Plural s that changes its sound',
    patternReminder:
      'The plural ending can sound like /s/, /z/ or /iz/, but the spelling still follows the ordinary plural pattern.',
    alternatives: ['s', 'es', 'z'],
    maskFrom: 'lastPart',
    introducedIn: 10,
    reviewPool: [
      aud('ps-r1', 'plural-sounds', 'lamps'),
      aud('ps-r2', 'plural-sounds', 'beds'),
      aud('ps-r3', 'plural-sounds', 'roses'),
      aud('ps-r4', 'plural-sounds', 'clocks'),
      aud('ps-r5', 'plural-sounds', 'snakes'),
      aud('ps-r6', 'plural-sounds', 'horses'),
      sort('ps-r7', 'plural-sounds', {
        'sounds like /s/': ['cats', 'clocks'],
        'sounds like /z/': ['dogs', 'beds'],
        'sounds like /iz/': ['buses', 'roses'],
      }),
      cloze('ps-r8', 'plural-sounds', 'The ___ in the garden smelled wonderful.', 'roses', { difficulty: 2 }),
      aud('ps-r9', 'plural-sounds', 'tables'),
      aud('ps-r10', 'plural-sounds', 'birds'),
      mistake('ps-r11', 'plural-sounds', 'Two horsez stood by the gate.', 'horsez', 'horses'),
      aud('ps-r12', 'plural-sounds', 'glasses', { difficulty: 2 }),
    ],
  },
  {
    id: 'er-est',
    label: 'Comparing with -er and -est',
    patternReminder:
      'Use "er" to compare two things and "est" for the most of all. Short words with one vowel and one consonant double that consonant first.',
    alternatives: ['er', 'est'],
    maskFrom: 'lastPart',
    introducedIn: 11,
    reviewPool: [
      aud('ee2-r1', 'er-est', 'taller'),
      aud('ee2-r2', 'er-est', 'quickest'),
      aud('ee2-r3', 'er-est', 'slower'),
      aud('ee2-r4', 'er-est', 'strongest'),
      aud('ee2-r5', 'er-est', 'hotter'),
      aud('ee2-r6', 'er-est', 'thinnest'),
      build('ee2-r7', 'er-est', ['big', '+est'], 'biggest'),
      build('ee2-r8', 'er-est', ['fast', '+er'], 'faster'),
      cloze('ee2-r9', 'er-est', 'That is the ___ tree in the whole park.', 'tallest', { difficulty: 2 }),
      mistake('ee2-r10', 'er-est', 'Today is hoter than yesterday.', 'hoter', 'hotter'),
      aud('ee2-r11', 'er-est', 'bigger'),
      aud('ee2-r12', 'er-est', 'thinner', { difficulty: 2 }),
    ],
  },
  {
    id: 'y-to-i',
    label: 'y becomes i before an ending',
    patternReminder:
      'When a word ends in a consonant and "y", change the y to i before adding an ending like "er", "est" or "ly".',
    alternatives: ['i', 'y'],
    maskFrom: 'lastPart',
    introducedIn: 12,
    reviewPool: [
      aud('yi2-r1', 'y-to-i', 'funnier'),
      aud('yi2-r2', 'y-to-i', 'luckiest'),
      aud('yi2-r3', 'y-to-i', 'heavier'),
      aud('yi2-r4', 'y-to-i', 'tidiest'),
      aud('yi2-r5', 'y-to-i', 'earlier'),
      aud('yi2-r6', 'y-to-i', 'noisier'),
      build('yi2-r7', 'y-to-i', ['happy', '+er'], 'happier'),
      build('yi2-r8', 'y-to-i', ['lucky', '+est'], 'luckiest'),
      cloze('yi2-r9', 'y-to-i', 'This bag is much ___ than mine.', 'heavier', { difficulty: 2 }),
      mistake('yi2-r10', 'y-to-i', 'That was the funnyest joke all day.', 'funnyest', 'funniest'),
      aud('yi2-r11', 'y-to-i', 'happiest'),
      aud('yi2-r12', 'y-to-i', 'tidier', { difficulty: 2 }),
    ],
  },
  {
    id: 'ly-suffix',
    label: 'The -ly ending',
    patternReminder:
      'Adding "ly" tells us how something happens. Keep the base word whole and add "ly" — unless it ends in consonant + y, which becomes i first.',
    maskFrom: 'lastPart',
    introducedIn: 13,
    reviewPool: [
      aud('ly-r1', 'ly-suffix', 'slowly'),
      aud('ly-r2', 'ly-suffix', 'kindly'),
      aud('ly-r3', 'ly-suffix', 'bravely'),
      aud('ly-r4', 'ly-suffix', 'loudly'),
      aud('ly-r5', 'ly-suffix', 'safely'),
      aud('ly-r6', 'ly-suffix', 'quietly'),
      build('ly-r7', 'ly-suffix', ['quick', '+ly'], 'quickly'),
      build('ly-r8', 'ly-suffix', ['happy', '+ly'], 'happily'),
      build('ly-r9', 'ly-suffix', ['angry', '+ly'], 'angrily'),
      cloze('ly-r10', 'ly-suffix', 'The door shut ___ behind us.', 'suddenly', { difficulty: 2 }),
      mistake('ly-r11', 'ly-suffix', 'She sang happyly all the way home.', 'happyly', 'happily'),
      aud('ly-r12', 'ly-suffix', 'easily', { difficulty: 2 }),
    ],
  },
  {
    id: 'silent-letters',
    label: 'Letters you cannot hear',
    patternReminder:
      'Some words begin with a letter you never say. Listen for the sound, then remember which silent partner it keeps: kn, wr, or mb at the end.',
    alternatives: ['kn', 'n', 'wr', 'r', 'mb', 'm'],
    introducedIn: 14,
    reviewPool: [
      aud('sl-r1', 'silent-letters', 'knee'),
      aud('sl-r2', 'silent-letters', 'knock'),
      aud('sl-r3', 'silent-letters', 'wrong'),
      aud('sl-r4', 'silent-letters', 'wrist'),
      aud('sl-r5', 'silent-letters', 'climb'),
      aud('sl-r6', 'silent-letters', 'crumb'),
      sort('sl-r7', 'silent-letters', {
        kn: ['knee', 'know'],
        wr: ['write', 'wrong'],
        mb: ['thumb', 'climb'],
      }),
      letters('sl-r8', 'silent-letters', 'knife'),
      letters('sl-r9', 'silent-letters', 'wrap'),
      cloze('sl-r10', 'silent-letters', 'I hurt my ___ falling off the swing.', 'knee', { difficulty: 2 }),
      aud('sl-r11', 'silent-letters', 'lamb'),
      aud('sl-r12', 'silent-letters', 'knight', { difficulty: 2 }),
    ],
  },
  {
    id: 'dge-ge',
    label: 'dge and ge',
    patternReminder:
      'At the end of a word, the /j/ sound is written "dge" straight after one short vowel, and "ge" everywhere else.',
    alternatives: ['dge', 'ge'],
    introducedIn: 15,
    reviewPool: [
      aud('dg-r1', 'dge-ge', 'badge'),
      aud('dg-r2', 'dge-ge', 'hedge'),
      aud('dg-r3', 'dge-ge', 'fudge'),
      aud('dg-r4', 'dge-ge', 'stage'),
      aud('dg-r5', 'dge-ge', 'cage'),
      aud('dg-r6', 'dge-ge', 'large'),
      sort('dg-r7', 'dge-ge', { dge: ['bridge', 'badge', 'edge'], ge: ['huge', 'stage', 'page'] }),
      pat('dg-r8', 'dge-ge', 'judge', { choices: ['dge', 'ge'] }),
      pat('dg-r9', 'dge-ge', 'change', { choices: ['ge', 'dge'] }),
      cloze('dg-r10', 'dge-ge', 'We walked across the wooden ___.', 'bridge', { difficulty: 2 }),
      aud('dg-r11', 'dge-ge', 'dodge', { difficulty: 2 }),
      aud('dg-r12', 'dge-ge', 'village', { difficulty: 3 }),
    ],
  },
  {
    id: 'tch-ch',
    label: 'tch and ch',
    patternReminder:
      'At the end of a short word, the /ch/ sound is written "tch" straight after one short vowel, and "ch" everywhere else.',
    alternatives: ['tch', 'ch'],
    introducedIn: 16,
    reviewPool: [
      aud('tc-r1', 'tch-ch', 'pitch'),
      aud('tc-r2', 'tch-ch', 'witch'),
      aud('tc-r3', 'tch-ch', 'stitch'),
      aud('tc-r4', 'tch-ch', 'beach'),
      aud('tc-r5', 'tch-ch', 'teach'),
      aud('tc-r6', 'tch-ch', 'bench'),
      sort('tc-r7', 'tch-ch', { tch: ['catch', 'match', 'pitch'], ch: ['much', 'beach', 'such'] }),
      pat('tc-r8', 'tch-ch', 'scratch', { choices: ['tch', 'ch'] }),
      pat('tc-r9', 'tch-ch', 'lunch', { choices: ['ch', 'tch'] }),
      cloze('tc-r10', 'tch-ch', 'Can you ___ the ball?', 'catch', { difficulty: 2 }),
      aud('tc-r11', 'tch-ch', 'sketch', { difficulty: 2 }),
      aud('tc-r12', 'tch-ch', 'rich'),
    ],
  },
]

export const CONCEPTS: ReadonlyMap<ConceptId, Concept> = new Map(
  CONCEPT_LIST.map((concept) => [concept.id, concept]),
)

export function conceptLabel(id: ConceptId): string {
  return CONCEPTS.get(id)?.label ?? id
}
