/**
 * The concept registry.
 *
 * Every concept carries the level-3 hint text, the rival spellings used at
 * hint level 5, and a review pool. The pool does double duty: cumulative
 * review in later exercises (spec §12) and the remediation questions the
 * engine injects when a child gets the concept wrong (spec §2).
 *
 * A pool must be deep enough that a repeated mistake always draws a word the
 * child has not just seen — that is what makes "prove it independently" real.
 */
import type { Concept, ConceptId } from '../spelling/types'
import { aud, build, cloze, dictate, family, letters, mistake, pat, proof, sort, syl } from './build'

const CONCEPT_LIST: Concept[] = [
  {
    id: 'syllables',
    label: 'Splitting words into beats',
    patternReminder: 'Clap the word. Each clap is a beat, and you spell one beat at a time.',
    introducedIn: 1,
    reviewPool: [
      syl('syl-r1', 'syllables', 'basket'),
      syl('syl-r2', 'syllables', 'jumper'),
      syl('syl-r3', 'syllables', 'picnic'),
      syl('syl-r4', 'syllables', 'magnet'),
      syl('syl-r5', 'syllables', 'tennis'),
      syl('syl-r6', 'syllables', 'garden'),
      syl('syl-r7', 'syllables', 'remember', { difficulty: 2 }),
      syl('syl-r8', 'syllables', 'important', { difficulty: 2 }),
      syl('syl-r9', 'syllables', 'yesterday', { difficulty: 2 }),
      syl('syl-r10', 'syllables', 'telescope', { difficulty: 3 }),
      aud('syl-r11', 'syllables', 'afternoon', { difficulty: 2 }),
      aud('syl-r12', 'syllables', 'lemonade', { difficulty: 2 }),
    ],
  },
  {
    id: 'ee-sound',
    label: 'The /ee/ sound',
    patternReminder:
      'The /ee/ sound has a few spellings. "ee" and "ea" usually sit inside a word, and "y" or "ey" usually come at the end.',
    alternatives: ['ee', 'ea', 'y', 'ey'],
    introducedIn: 2,
    reviewPool: [
      aud('ee-r1', 'ee-sound', 'sheep'),
      aud('ee-r2', 'ee-sound', 'dream'),
      aud('ee-r3', 'ee-sound', 'queen'),
      aud('ee-r4', 'ee-sound', 'treat'),
      aud('ee-r5', 'ee-sound', 'sunny'),
      aud('ee-r6', 'ee-sound', 'donkey'),
      pat('ee-r7', 'ee-sound', 'green', { choices: ['ee', 'ea'] }),
      pat('ee-r8', 'ee-sound', 'clean', { choices: ['ea', 'ee'] }),
      pat('ee-r9', 'ee-sound', 'twenty', { choices: ['y', 'ey'] }),
      letters('ee-r10', 'ee-sound', 'between', { difficulty: 2 }),
      letters('ee-r11', 'ee-sound', 'teacher', { difficulty: 2 }),
      cloze('ee-r12', 'ee-sound', 'We go swimming once a ___.', 'week', { difficulty: 2 }),
      aud('ee-r13', 'ee-sound', 'cheese'),
      aud('ee-r14', 'ee-sound', 'valley', { difficulty: 2 }),
    ],
  },
  {
    id: 'oa-sound',
    label: 'The /oa/ sound',
    patternReminder:
      'The /oa/ sound has several spellings. "oa" usually sits inside a word, while "ow", "oe" and o_e often come near the end.',
    alternatives: ['oa', 'ow', 'oe', 'o'],
    introducedIn: 3,
    reviewPool: [
      aud('oa-r1', 'oa-sound', 'goat'),
      aud('oa-r2', 'oa-sound', 'toast'),
      aud('oa-r3', 'oa-sound', 'yellow'),
      aud('oa-r4', 'oa-sound', 'elbow'),
      aud('oa-r5', 'oa-sound', 'stone'),
      aud('oa-r6', 'oa-sound', 'rope'),
      pat('oa-r7', 'oa-sound', 'road', { choices: ['oa', 'ow'] }),
      pat('oa-r8', 'oa-sound', 'snow', { choices: ['ow', 'oa'] }),
      letters('oa-r9', 'oa-sound', 'float', { difficulty: 2 }),
      letters('oa-r10', 'oa-sound', 'pillow', { difficulty: 2 }),
      aud('oa-r11', 'oa-sound', 'throat', { difficulty: 2 }),
      aud('oa-r12', 'oa-sound', 'tiptoe', { difficulty: 2 }),
      cloze('oa-r13', 'oa-sound', 'There is a ___ in my sock.', 'hole', { difficulty: 2 }),
      aud('oa-r14', 'oa-sound', 'smoke'),
    ],
  },
  {
    id: 'plural-s-es',
    label: 'Plurals with -s and -es',
    patternReminder:
      'Most words just add "s". If the word already ends in a hissing or buzzing sound — s, sh, ch, x or z — it needs "es".',
    alternatives: ['s', 'es'],
    introducedIn: 4,
    reviewPool: [
      aud('pl-r1', 'plural-s-es', 'foxes'),
      aud('pl-r2', 'plural-s-es', 'dishes'),
      aud('pl-r3', 'plural-s-es', 'benches'),
      aud('pl-r4', 'plural-s-es', 'glasses'),
      aud('pl-r5', 'plural-s-es', 'books'),
      aud('pl-r6', 'plural-s-es', 'chairs'),
      cloze('pl-r7', 'plural-s-es', 'We waited at the stop for two ___.', 'buses', { difficulty: 2 }),
      cloze('pl-r8', 'plural-s-es', 'There are three ___ on the shelf.', 'boxes', { difficulty: 2 }),
      sort('pl-r9', 'plural-s-es', { '+s': ['trees', 'hands'], '+es': ['wishes', 'matches'] }),
      mistake('pl-r10', 'plural-s-es', 'We washed all the dishs after dinner.', 'dishs', 'dishes', { difficulty: 2 }),
      aud('pl-r11', 'plural-s-es', 'churches', { difficulty: 2 }),
      aud('pl-r12', 'plural-s-es', 'taxes', { difficulty: 3 }),
    ],
  },
  {
    id: 'plural-y-ies',
    label: 'Words ending in y',
    patternReminder:
      'If a consonant comes before the "y", change the y to i and add "es". If a vowel comes before the y, just add "s".',
    alternatives: ['ies', 'ys'],
    introducedIn: 5,
    reviewPool: [
      aud('yi-r1', 'plural-y-ies', 'cherries'),
      aud('yi-r2', 'plural-y-ies', 'parties'),
      aud('yi-r3', 'plural-y-ies', 'ladies'),
      aud('yi-r4', 'plural-y-ies', 'puppies'),
      aud('yi-r5', 'plural-y-ies', 'keys'),
      aud('yi-r6', 'plural-y-ies', 'monkeys'),
      cloze('yi-r7', 'plural-y-ies', 'The two ___ were fast asleep.', 'babies', { difficulty: 2 }),
      cloze('yi-r8', 'plural-y-ies', 'We visited three different ___.', 'countries', { difficulty: 3 }),
      sort('yi-r9', 'plural-y-ies', { 'y becomes ies': ['stories', 'pennies'], 'just add s': ['days', 'toys'] }),
      mistake('yi-r10', 'plural-y-ies', 'The butterflys landed on the flowers.', 'butterflys', 'butterflies', {
        difficulty: 2,
      }),
      aud('yi-r11', 'plural-y-ies', 'armies', { difficulty: 2 }),
      aud('yi-r12', 'plural-y-ies', 'valleys', { difficulty: 2 }),
    ],
  },
  {
    id: 'compound-words',
    label: 'Compound words',
    patternReminder:
      'Find the two smaller words hiding inside. Each one usually keeps its own spelling exactly as it was.',
    maskFrom: 'lastPart',
    introducedIn: 6,
    reviewPool: [
      aud('cw-r1', 'compound-words', 'toothbrush'),
      aud('cw-r2', 'compound-words', 'playground'),
      aud('cw-r3', 'compound-words', 'sunflower'),
      aud('cw-r4', 'compound-words', 'snowman'),
      aud('cw-r5', 'compound-words', 'notebook'),
      aud('cw-r6', 'compound-words', 'weekend'),
      build('cw-r7', 'compound-words', ['camp', 'fire'], 'campfire'),
      build('cw-r8', 'compound-words', ['door', 'bell'], 'doorbell'),
      build('cw-r9', 'compound-words', ['pop', 'corn'], 'popcorn'),
      cloze('cw-r10', 'compound-words', 'I finished my ___ before dinner.', 'homework', { difficulty: 2 }),
      aud('cw-r11', 'compound-words', 'blackboard', { difficulty: 2 }),
      aud('cw-r12', 'compound-words', 'skyscraper', { difficulty: 3 }),
    ],
  },
  {
    id: 'consonant-doubling',
    label: 'Doubling the last consonant',
    patternReminder:
      'Short word, one vowel then one consonant, and the ending starts with a vowel? Double that last consonant.',
    alternatives: ['nn', 'n', 'pp', 'p', 'tt', 't'],
    introducedIn: 7,
    reviewPool: [
      aud('cd-r1', 'consonant-doubling', 'swimming'),
      aud('cd-r2', 'consonant-doubling', 'shopping'),
      aud('cd-r3', 'consonant-doubling', 'clapping'),
      aud('cd-r4', 'consonant-doubling', 'dropped'),
      aud('cd-r5', 'consonant-doubling', 'jogging'),
      aud('cd-r6', 'consonant-doubling', 'winning'),
      build('cd-r7', 'consonant-doubling', ['hug', '+ing'], 'hugging'),
      build('cd-r8', 'consonant-doubling', ['chat', '+ing'], 'chatting'),
      cloze('cd-r9', 'consonant-doubling', 'She was ___ across the puddles.', 'skipping', { difficulty: 2 }),
      mistake('cd-r10', 'consonant-doubling', 'The bus stoped at the corner.', 'stoped', 'stopped'),
      aud('cd-r11', 'consonant-doubling', 'grabbing', { difficulty: 2 }),
      aud('cd-r12', 'consonant-doubling', 'tripping', { difficulty: 2 }),
    ],
  },
  {
    id: 'drop-silent-e',
    label: 'Dropping the silent e',
    patternReminder:
      'If the word ends in a silent e and the ending starts with a vowel, the e is not needed any more. Drop it.',
    introducedIn: 8,
    reviewPool: [
      aud('de-r1', 'drop-silent-e', 'baking'),
      aud('de-r2', 'drop-silent-e', 'riding'),
      aud('de-r3', 'drop-silent-e', 'smiling'),
      aud('de-r4', 'drop-silent-e', 'moving'),
      aud('de-r5', 'drop-silent-e', 'closing'),
      aud('de-r6', 'drop-silent-e', 'shining'),
      build('de-r7', 'drop-silent-e', ['dance', '+ing'], 'dancing'),
      build('de-r8', 'drop-silent-e', ['drive', '+ing'], 'driving'),
      cloze('de-r9', 'drop-silent-e', 'He is ___ a letter to his cousin.', 'writing', { difficulty: 2 }),
      mistake('de-r10', 'drop-silent-e', 'We are makeing a cake.', 'makeing', 'making'),
      aud('de-r11', 'drop-silent-e', 'saving', { difficulty: 2 }),
      aud('de-r12', 'drop-silent-e', 'using', { difficulty: 2 }),
    ],
  },
  {
    id: 'ed-endings',
    label: 'The -ed ending',
    patternReminder:
      'Past-tense words almost always end in "ed", even when it sounds like /t/ or /d/ or adds a whole beat.',
    alternatives: ['ed', 't', 'd'],
    maskFrom: 'lastPart',
    introducedIn: 9,
    reviewPool: [
      aud('ed-r1', 'ed-endings', 'walked'),
      aud('ed-r2', 'ed-endings', 'landed'),
      aud('ed-r3', 'ed-endings', 'kicked'),
      aud('ed-r4', 'ed-endings', 'shouted'),
      aud('ed-r5', 'ed-endings', 'cleaned'),
      aud('ed-r6', 'ed-endings', 'pointed'),
      sort('ed-r7', 'ed-endings', {
        'sounds like /t/': ['jumped', 'walked'],
        'sounds like /d/': ['played', 'cleaned'],
        'adds a beat': ['wanted', 'landed'],
      }),
      cloze('ed-r8', 'ed-endings', 'We ___ for the bus in the rain.', 'waited', { difficulty: 2 }),
      mistake('ed-r9', 'ed-endings', 'She jumpt over the puddle.', 'jumpt', 'jumped'),
      aud('ed-r10', 'ed-endings', 'painted', { difficulty: 2 }),
      aud('ed-r11', 'ed-endings', 'helped', { difficulty: 2 }),
      build('ed-r12', 'ed-endings', ['want', '+ed'], 'wanted'),
    ],
  },
  {
    id: 'plural-sounds',
    label: 'Plural s that changes its sound',
    patternReminder:
      'The plural ending can sound like /s/, /z/ or /iz/, but the spelling still follows the ordinary plural pattern.',
    alternatives: ['s', 'es', 'z'],
    maskFrom: 'lastPart',
    introducedIn: 10,
    reviewPool: [
      aud('ps-r1', 'plural-sounds', 'lamps'),
      aud('ps-r2', 'plural-sounds', 'beds'),
      aud('ps-r3', 'plural-sounds', 'roses'),
      aud('ps-r4', 'plural-sounds', 'clocks'),
      aud('ps-r5', 'plural-sounds', 'snakes'),
      aud('ps-r6', 'plural-sounds', 'horses'),
      sort('ps-r7', 'plural-sounds', {
        'sounds like /s/': ['cats', 'clocks'],
        'sounds like /z/': ['dogs', 'beds'],
        'sounds like /iz/': ['buses', 'roses'],
      }),
      cloze('ps-r8', 'plural-sounds', 'The ___ in the garden smelled wonderful.', 'roses', { difficulty: 2 }),
      aud('ps-r9', 'plural-sounds', 'tables'),
      aud('ps-r10', 'plural-sounds', 'birds'),
      mistake('ps-r11', 'plural-sounds', 'Two horsez stood by the gate.', 'horsez', 'horses'),
      aud('ps-r12', 'plural-sounds', 'glasses', { difficulty: 2 }),
    ],
  },
  {
    id: 'er-est',
    label: 'Comparing with -er and -est',
    patternReminder:
      'Use "er" to compare two things and "est" for the most of all. Short words with one vowel and one consonant double that consonant first.',
    alternatives: ['er', 'est'],
    maskFrom: 'lastPart',
    introducedIn: 11,
    reviewPool: [
      aud('ee2-r1', 'er-est', 'taller'),
      aud('ee2-r2', 'er-est', 'quickest'),
      aud('ee2-r3', 'er-est', 'slower'),
      aud('ee2-r4', 'er-est', 'strongest'),
      aud('ee2-r5', 'er-est', 'hotter'),
      aud('ee2-r6', 'er-est', 'thinnest'),
      build('ee2-r7', 'er-est', ['big', '+est'], 'biggest'),
      build('ee2-r8', 'er-est', ['fast', '+er'], 'faster'),
      cloze('ee2-r9', 'er-est', 'That is the ___ tree in the whole park.', 'tallest', { difficulty: 2 }),
      mistake('ee2-r10', 'er-est', 'Today is hoter than yesterday.', 'hoter', 'hotter'),
      aud('ee2-r11', 'er-est', 'bigger'),
      aud('ee2-r12', 'er-est', 'thinner', { difficulty: 2 }),
    ],
  },
  {
    id: 'y-to-i',
    label: 'y becomes i before an ending',
    patternReminder:
      'When a word ends in a consonant and "y", change the y to i before adding an ending like "er", "est" or "ly".',
    alternatives: ['i', 'y'],
    maskFrom: 'lastPart',
    introducedIn: 12,
    reviewPool: [
      aud('yi2-r1', 'y-to-i', 'funnier'),
      aud('yi2-r2', 'y-to-i', 'luckiest'),
      aud('yi2-r3', 'y-to-i', 'heavier'),
      aud('yi2-r4', 'y-to-i', 'tidiest'),
      aud('yi2-r5', 'y-to-i', 'earlier'),
      aud('yi2-r6', 'y-to-i', 'noisier'),
      build('yi2-r7', 'y-to-i', ['happy', '+er'], 'happier'),
      build('yi2-r8', 'y-to-i', ['lucky', '+est'], 'luckiest'),
      cloze('yi2-r9', 'y-to-i', 'This bag is much ___ than mine.', 'heavier', { difficulty: 2 }),
      mistake('yi2-r10', 'y-to-i', 'That was the funnyest joke all day.', 'funnyest', 'funniest'),
      aud('yi2-r11', 'y-to-i', 'happiest'),
      aud('yi2-r12', 'y-to-i', 'tidier', { difficulty: 2 }),
    ],
  },
  {
    id: 'ly-suffix',
    label: 'The -ly ending',
    patternReminder:
      'Adding "ly" tells us how something happens. Keep the base word whole and add "ly" — unless it ends in consonant + y, which becomes i first.',
    maskFrom: 'lastPart',
    introducedIn: 13,
    reviewPool: [
      aud('ly-r1', 'ly-suffix', 'slowly'),
      aud('ly-r2', 'ly-suffix', 'kindly'),
      aud('ly-r3', 'ly-suffix', 'bravely'),
      aud('ly-r4', 'ly-suffix', 'loudly'),
      aud('ly-r5', 'ly-suffix', 'safely'),
      aud('ly-r6', 'ly-suffix', 'quietly'),
      build('ly-r7', 'ly-suffix', ['quick', '+ly'], 'quickly'),
      build('ly-r8', 'ly-suffix', ['happy', '+ly'], 'happily'),
      build('ly-r9', 'ly-suffix', ['angry', '+ly'], 'angrily'),
      cloze('ly-r10', 'ly-suffix', 'The door shut ___ behind us.', 'suddenly', { difficulty: 2 }),
      mistake('ly-r11', 'ly-suffix', 'She sang happyly all the way home.', 'happyly', 'happily'),
      aud('ly-r12', 'ly-suffix', 'easily', { difficulty: 2 }),
    ],
  },
  {
    id: 'silent-letters',
    label: 'Letters you cannot hear',
    patternReminder:
      'Some words begin with a letter you never say. Listen for the sound, then remember which silent partner it keeps: kn, wr, or mb at the end.',
    alternatives: ['kn', 'n', 'wr', 'r', 'mb', 'm'],
    introducedIn: 14,
    reviewPool: [
      aud('sl-r1', 'silent-letters', 'knee'),
      aud('sl-r2', 'silent-letters', 'knock'),
      aud('sl-r3', 'silent-letters', 'wrong'),
      aud('sl-r4', 'silent-letters', 'wrist'),
      aud('sl-r5', 'silent-letters', 'climb'),
      aud('sl-r6', 'silent-letters', 'crumb'),
      sort('sl-r7', 'silent-letters', {
        kn: ['knee', 'know'],
        wr: ['write', 'wrong'],
        mb: ['thumb', 'climb'],
      }),
      letters('sl-r8', 'silent-letters', 'knife'),
      letters('sl-r9', 'silent-letters', 'wrap'),
      cloze('sl-r10', 'silent-letters', 'I hurt my ___ falling off the swing.', 'knee', { difficulty: 2 }),
      aud('sl-r11', 'silent-letters', 'lamb'),
      aud('sl-r12', 'silent-letters', 'knight', { difficulty: 2 }),
    ],
  },
  {
    id: 'dge-ge',
    label: 'dge and ge',
    patternReminder:
      'At the end of a word, the /j/ sound is written "dge" straight after one short vowel, and "ge" everywhere else.',
    alternatives: ['dge', 'ge'],
    introducedIn: 15,
    reviewPool: [
      aud('dg-r1', 'dge-ge', 'badge'),
      aud('dg-r2', 'dge-ge', 'hedge'),
      aud('dg-r3', 'dge-ge', 'fudge'),
      aud('dg-r4', 'dge-ge', 'stage'),
      aud('dg-r5', 'dge-ge', 'cage'),
      aud('dg-r6', 'dge-ge', 'large'),
      sort('dg-r7', 'dge-ge', { dge: ['bridge', 'badge', 'edge'], ge: ['huge', 'stage', 'page'] }),
      pat('dg-r8', 'dge-ge', 'judge', { choices: ['dge', 'ge'] }),
      pat('dg-r9', 'dge-ge', 'change', { choices: ['ge', 'dge'] }),
      cloze('dg-r10', 'dge-ge', 'We walked across the wooden ___.', 'bridge', { difficulty: 2 }),
      aud('dg-r11', 'dge-ge', 'dodge', { difficulty: 2 }),
      aud('dg-r12', 'dge-ge', 'village', { difficulty: 3 }),
    ],
  },
  {
    id: 'tch-ch',
    label: 'tch and ch',
    patternReminder:
      'At the end of a short word, the /ch/ sound is written "tch" straight after one short vowel, and "ch" everywhere else.',
    alternatives: ['tch', 'ch'],
    introducedIn: 16,
    reviewPool: [
      aud('tc-r1', 'tch-ch', 'pitch'),
      aud('tc-r2', 'tch-ch', 'witch'),
      aud('tc-r3', 'tch-ch', 'stitch'),
      aud('tc-r4', 'tch-ch', 'beach'),
      aud('tc-r5', 'tch-ch', 'teach'),
      aud('tc-r6', 'tch-ch', 'bench'),
      sort('tc-r7', 'tch-ch', { tch: ['catch', 'match', 'pitch'], ch: ['much', 'beach', 'such'] }),
      pat('tc-r8', 'tch-ch', 'scratch', { choices: ['tch', 'ch'] }),
      pat('tc-r9', 'tch-ch', 'lunch', { choices: ['ch', 'tch'] }),
      cloze('tc-r10', 'tch-ch', 'Can you ___ the ball?', 'catch', { difficulty: 2 }),
      aud('tc-r11', 'tch-ch', 'sketch', { difficulty: 2 }),
      aud('tc-r12', 'tch-ch', 'rich'),
    ],
  },
  {
    id: 'prefix-re-un',
    label: 'The prefixes re- and un-',
    patternReminder:
      'A prefix goes in front of a whole word and does not change its spelling. "re-" usually means again, "un-" usually means not.',
    maskFrom: 'firstPart',
    introducedIn: 17,
    reviewPool: [
      aud('ru-r1', 'prefix-re-un', 'rebuild'),
      aud('ru-r2', 'prefix-re-un', 'refill'),
      aud('ru-r3', 'prefix-re-un', 'unkind'),
      aud('ru-r4', 'prefix-re-un', 'unlock'),
      aud('ru-r5', 'prefix-re-un', 'unfair'),
      aud('ru-r6', 'prefix-re-un', 'replay'),
      build('ru-r7', 'prefix-re-un', ['re', 'read'], 'reread'),
      build('ru-r8', 'prefix-re-un', ['un', 'happy'], 'unhappy'),
      cloze('ru-r9', 'prefix-re-un', 'Please ___ the door before you go.', 'unlock', { difficulty: 2 }),
      mistake('ru-r10', 'prefix-re-un', 'That decision was very unfare.', 'unfare', 'unfair'),
      aud('ru-r11', 'prefix-re-un', 'untie', { difficulty: 2 }),
      aud('ru-r12', 'prefix-re-un', 'return'),
    ],
  },
  {
    id: 'prefix-mis-dis-pre',
    label: 'The prefixes mis-, dis- and pre-',
    patternReminder:
      'Prefixes change what a word means but leave the base word spelled exactly as it was — even when that gives you a double letter.',
    maskFrom: 'firstPart',
    introducedIn: 18,
    reviewPool: [
      aud('mdp-r1', 'prefix-mis-dis-pre', 'mistake'),
      aud('mdp-r2', 'prefix-mis-dis-pre', 'misplace'),
      aud('mdp-r3', 'prefix-mis-dis-pre', 'dislike'),
      aud('mdp-r4', 'prefix-mis-dis-pre', 'disappear'),
      aud('mdp-r5', 'prefix-mis-dis-pre', 'preheat'),
      aud('mdp-r6', 'prefix-mis-dis-pre', 'preview'),
      build('mdp-r7', 'prefix-mis-dis-pre', ['dis', 'agree'], 'disagree'),
      build('mdp-r8', 'prefix-mis-dis-pre', ['mis', 'behave'], 'misbehave'),
      build('mdp-r9', 'prefix-mis-dis-pre', ['mis', 'spell'], 'misspell'),
      cloze('mdp-r10', 'prefix-mis-dis-pre', 'I ___ with almost everything he said.', 'disagree', { difficulty: 2 }),
      aud('mdp-r11', 'prefix-mis-dis-pre', 'disobey', { difficulty: 2 }),
      aud('mdp-r12', 'prefix-mis-dis-pre', 'dishonest', { difficulty: 3 }),
    ],
  },
  {
    id: 'prefix-meaning',
    label: 'Prefixes that carry meaning',
    patternReminder:
      'Prefixes carry meaning: "sub-" and "under-" mean below, "de-" means undo or remove, "anti-" means against.',
    maskFrom: 'firstPart',
    introducedIn: 19,
    reviewPool: [
      aud('pm-r1', 'prefix-meaning', 'subway'),
      aud('pm-r2', 'prefix-meaning', 'underwater'),
      aud('pm-r3', 'prefix-meaning', 'underline'),
      aud('pm-r4', 'prefix-meaning', 'defrost'),
      aud('pm-r5', 'prefix-meaning', 'submarine'),
      aud('pm-r6', 'prefix-meaning', 'underground'),
      build('pm-r7', 'prefix-meaning', ['sub', 'tract'], 'subtract'),
      build('pm-r8', 'prefix-meaning', ['anti', 'venom'], 'antivenom'),
      cloze('pm-r9', 'prefix-meaning', 'The tunnel runs ___ the whole city.', 'underground', { difficulty: 2 }),
      aud('pm-r10', 'prefix-meaning', 'depart', { difficulty: 2 }),
      aud('pm-r11', 'prefix-meaning', 'deactivate', { difficulty: 3 }),
      aud('pm-r12', 'prefix-meaning', 'understand'),
    ],
  },
  {
    id: 'suffix-ful-less',
    label: 'The endings -ful and -less',
    patternReminder:
      '"ful" means full of and "less" means without. The ending "ful" has only one l, even though the word "full" has two.',
    alternatives: ['ful', 'full', 'less'],
    maskFrom: 'lastPart',
    introducedIn: 20,
    reviewPool: [
      aud('fl-r1', 'suffix-ful-less', 'cheerful'),
      aud('fl-r2', 'suffix-ful-less', 'useful'),
      aud('fl-r3', 'suffix-ful-less', 'playful'),
      aud('fl-r4', 'suffix-ful-less', 'endless'),
      aud('fl-r5', 'suffix-ful-less', 'harmless'),
      aud('fl-r6', 'suffix-ful-less', 'hopeless'),
      build('fl-r7', 'suffix-ful-less', ['help', 'ful'], 'helpful'),
      build('fl-r8', 'suffix-ful-less', ['fear', 'less'], 'fearless'),
      cloze('fl-r9', 'suffix-ful-less', 'The painting was bright and ___.', 'colourful', { difficulty: 2 }),
      mistake('fl-r10', 'suffix-ful-less', 'That was a very helpfull answer.', 'helpfull', 'helpful'),
      aud('fl-r11', 'suffix-ful-less', 'careless'),
      aud('fl-r12', 'suffix-ful-less', 'careful'),
    ],
  },
  {
    id: 'suffix-ness',
    label: 'The ending -ness',
    patternReminder:
      '"ness" turns a describing word into a thing. Keep the base word whole — unless it ends in consonant + y, which becomes i first.',
    maskFrom: 'lastPart',
    introducedIn: 21,
    reviewPool: [
      aud('ns-r1', 'suffix-ness', 'sadness'),
      aud('ns-r2', 'suffix-ness', 'illness'),
      aud('ns-r3', 'suffix-ness', 'goodness'),
      aud('ns-r4', 'suffix-ness', 'fitness'),
      aud('ns-r5', 'suffix-ness', 'weakness'),
      aud('ns-r6', 'suffix-ness', 'brightness'),
      build('ns-r7', 'suffix-ness', ['kind', 'ness'], 'kindness'),
      build('ns-r8', 'suffix-ness', ['happy', 'ness'], 'happiness'),
      cloze('ns-r9', 'suffix-ness', 'We waited in the ___ for our eyes to adjust.', 'darkness', { difficulty: 2 }),
      mistake('ns-r10', 'suffix-ness', 'Her happyness was obvious.', 'happyness', 'happiness'),
      aud('ns-r11', 'suffix-ness', 'darkness'),
      aud('ns-r12', 'suffix-ness', 'laziness', { difficulty: 3 }),
    ],
  },
  {
    id: 'suffix-ment',
    label: 'The ending -ment',
    patternReminder:
      '"ment" turns an action into a thing or a result. It starts with a consonant, so the base word usually keeps its final e.',
    maskFrom: 'lastPart',
    introducedIn: 22,
    reviewPool: [
      aud('mt-r1', 'suffix-ment', 'payment'),
      aud('mt-r2', 'suffix-ment', 'treatment'),
      aud('mt-r3', 'suffix-ment', 'agreement'),
      aud('mt-r4', 'suffix-ment', 'movement'),
      aud('mt-r5', 'suffix-ment', 'equipment'),
      aud('mt-r6', 'suffix-ment', 'argument'),
      build('mt-r7', 'suffix-ment', ['enjoy', 'ment'], 'enjoyment'),
      build('mt-r8', 'suffix-ment', ['excite', 'ment'], 'excitement'),
      cloze('mt-r9', 'suffix-ment', 'We took a careful ___ of the room.', 'measurement', { difficulty: 2 }),
      mistake('mt-r10', 'suffix-ment', 'The excitment was too much.', 'excitment', 'excitement'),
      aud('mt-r11', 'suffix-ment', 'measurement', { difficulty: 2 }),
      aud('mt-r12', 'suffix-ment', 'excitement'),
    ],
  },
  {
    id: 'suffix-ous',
    label: 'The ending -ous',
    patternReminder:
      '"ous" makes a describing word. It always ends in "ous", never "us", however much it sounds like it.',
    alternatives: ['ous', 'us'],
    maskFrom: 'lastPart',
    introducedIn: 23,
    reviewPool: [
      aud('os-r1', 'suffix-ous', 'famous'),
      aud('os-r2', 'suffix-ous', 'nervous'),
      aud('os-r3', 'suffix-ous', 'poisonous'),
      aud('os-r4', 'suffix-ous', 'jealous'),
      aud('os-r5', 'suffix-ous', 'joyous'),
      aud('os-r6', 'suffix-ous', 'serious'),
      cloze('os-r7', 'suffix-ous', 'That cliff edge looks ___.', 'dangerous', { difficulty: 2 }),
      cloze('os-r8', 'suffix-ous', 'Some frogs are brightly coloured and ___.', 'poisonous', { difficulty: 3 }),
      mistake('os-r9', 'suffix-ous', 'The snake was very dangerus.', 'dangerus', 'dangerous'),
      aud('os-r10', 'suffix-ous', 'dangerous'),
      aud('os-r11', 'suffix-ous', 'humorous', { difficulty: 3 }),
      aud('os-r12', 'suffix-ous', 'courageous', { difficulty: 3 }),
    ],
  },
  {
    id: 'word-families',
    label: 'Building word families',
    patternReminder:
      'Find the base word first. Prefixes go in front of it and suffixes go after it, and the base word usually keeps its own spelling.',
    introducedIn: 24,
    reviewPool: [
      build('wf-r1', 'word-families', ['un', 'help', 'ful'], 'unhelpful'),
      build('wf-r2', 'word-families', ['help', 'ful', 'ness'], 'helpfulness'),
      build('wf-r3', 'word-families', ['un', 'kind', 'ness'], 'unkindness'),
      build('wf-r4', 'word-families', ['care', 'less', 'ness'], 'carelessness'),
      build('wf-r5', 'word-families', ['thought', 'less'], 'thoughtless'),
      build('wf-r6', 'word-families', ['thought', 'ful'], 'thoughtful'),
      family('wf-r7', 'word-families', 'care', [
        ['full of care', 'careful'],
        ['without care', 'careless'],
      ]),
      family('wf-r8', 'word-families', 'hope', [
        ['full of hope', 'hopeful'],
        ['without hope', 'hopeless'],
      ]),
      aud('wf-r9', 'word-families', 'unhelpful', { difficulty: 2 }),
      aud('wf-r10', 'word-families', 'unhelpfulness', { difficulty: 3 }),
      aud('wf-r11', 'word-families', 'hopefulness', { difficulty: 3 }),
      aud('wf-r12', 'word-families', 'uncareful', { difficulty: 2 }),
    ],
  },
  {
    id: 'homophones-there',
    label: 'there / their / they’re',
    patternReminder:
      '"there" is a place — it has "here" inside it. "their" belongs to them. "they’re" is short for "they are".',
    alternatives: ['there', 'their', "they're"],
    introducedIn: 25,
    reviewPool: [
      cloze('ht-r1', 'homophones-there', 'The children left ___ bags in the hall.', 'their'),
      cloze('ht-r2', 'homophones-there', 'Wait over ___ by the gate.', 'there'),
      cloze('ht-r3', 'homophones-there', '___ already at the park.', "they're"),
      cloze('ht-r4', 'homophones-there', 'Is ___ any milk left?', 'there'),
      cloze('ht-r5', 'homophones-there', 'I like ___ new house.', 'their'),
      cloze('ht-r6', 'homophones-there', '___ going to be late again.', "they're"),
      mistake('ht-r7', 'homophones-there', 'Their going to the beach today.', 'Their', "They're"),
      mistake('ht-r8', 'homophones-there', 'The dogs ate they\'re dinner.', "they're", 'their'),
      aud('ht-r9', 'homophones-there', 'their', { withSentence: true, difficulty: 2 }),
      aud('ht-r10', 'homophones-there', 'there', { withSentence: true, difficulty: 2 }),
      dictate('ht-r11', 'homophones-there', 'They left their coats over there.', { difficulty: 3 }),
      dictate('ht-r12', 'homophones-there', "They're waiting by their car.", { difficulty: 3 }),
    ],
  },
  {
    id: 'homophones-to-too-two',
    label: 'to / too / two',
    patternReminder:
      '"two" is the number — it has a w like twin and twice. "too" means also or more than enough, with an extra o. "to" does all the other jobs.',
    alternatives: ['to', 'too', 'two'],
    introducedIn: 26,
    reviewPool: [
      cloze('tt-r1', 'homophones-to-too-two', 'I have ___ brothers.', 'two'),
      cloze('tt-r2', 'homophones-to-too-two', 'That bag is far ___ heavy.', 'too'),
      cloze('tt-r3', 'homophones-to-too-two', 'We walked ___ the shop.', 'to'),
      cloze('tt-r4', 'homophones-to-too-two', 'Can I come ___?', 'too'),
      cloze('tt-r5', 'homophones-to-too-two', 'She gave it ___ me.', 'to'),
      cloze('tt-r6', 'homophones-to-too-two', 'There are ___ cats on the fence.', 'two'),
      mistake('tt-r7', 'homophones-to-too-two', 'I have two much homework.', 'two', 'too'),
      mistake('tt-r8', 'homophones-to-too-two', 'We went too the park.', 'too', 'to'),
      dictate('tt-r9', 'homophones-to-too-two', 'The two of us went to the shop too.', { difficulty: 3 }),
      aud('tt-r10', 'homophones-to-too-two', 'too', { withSentence: true, difficulty: 2 }),
      aud('tt-r11', 'homophones-to-too-two', 'two', { withSentence: true, difficulty: 2 }),
      cloze('tt-r12', 'homophones-to-too-two', 'It was ___ dark ___ see.', 'too', { difficulty: 3 }),
    ],
  },
  {
    id: 'apostrophe-pairs',
    label: 'your / you’re and its / it’s',
    patternReminder:
      'The apostrophe stands in for missing letters. "you’re" is "you are" and "it’s" is "it is". Without an apostrophe, the word shows belonging.',
    alternatives: ['your', "you're", 'its', "it's"],
    introducedIn: 27,
    reviewPool: [
      cloze('ap-r1', 'apostrophe-pairs', 'Is this ___ jumper?', 'your'),
      cloze('ap-r2', 'apostrophe-pairs', '___ going to enjoy this.', "You're"),
      cloze('ap-r3', 'apostrophe-pairs', 'The dog wagged ___ tail.', 'its'),
      cloze('ap-r4', 'apostrophe-pairs', '___ raining again.', "It's"),
      cloze('ap-r5', 'apostrophe-pairs', 'I think ___ right about that.', "you're"),
      cloze('ap-r6', 'apostrophe-pairs', 'The bird built ___ nest in the gutter.', 'its'),
      mistake('ap-r7', 'apostrophe-pairs', 'Your going to be late.', 'Your', "You're"),
      mistake('ap-r8', 'apostrophe-pairs', 'The cat licked it\'s paw.', "it's", 'its'),
      build('ap-r9', 'apostrophe-pairs', ['you', 'are'], "you're"),
      build('ap-r10', 'apostrophe-pairs', ['it', 'is'], "it's"),
      dictate('ap-r11', 'apostrophe-pairs', "It's your turn now.", { difficulty: 3 }),
      dictate('ap-r12', 'apostrophe-pairs', "You're sure it's yours?", { difficulty: 3 }),
    ],
  },
  {
    id: 'homophones-more',
    label: 'More homophones',
    patternReminder:
      'These words sound identical, so your ears cannot help. Think about what the sentence means, then pick the spelling that fits.',
    introducedIn: 28,
    reviewPool: [
      cloze('hm-r1', 'homophones-more', 'Can you ___ the music?', 'hear'),
      cloze('hm-r2', 'homophones-more', 'Come and sit ___ with me.', 'here'),
      cloze('hm-r3', 'homophones-more', 'Our team ___ the final.', 'won'),
      cloze('hm-r4', 'homophones-more', 'I only need ___ more.', 'one'),
      cloze('hm-r5', 'homophones-more', 'I ate a ___ of cake.', 'piece'),
      cloze('hm-r6', 'homophones-more', 'Please ___ your name at the top.', 'write'),
      cloze('hm-r7', 'homophones-more', 'Turn ___ at the corner.', 'right'),
      cloze('hm-r8', 'homophones-more', 'The wind ___ all night.', 'blew'),
      mistake('hm-r9', 'homophones-more', 'Can you here the music?', 'here', 'hear'),
      mistake('hm-r10', 'homophones-more', 'I one the race.', 'one', 'won'),
      aud('hm-r11', 'homophones-more', 'piece', { withSentence: true, difficulty: 2 }),
      aud('hm-r12', 'homophones-more', 'flour', { withSentence: true, difficulty: 3 }),
    ],
  },
  {
    id: 'homophone-proofreading',
    label: 'Spotting the wrong homophone',
    patternReminder:
      'Every word here is a real word, so nothing looks misspelled. Read the sentence for its meaning and check each word does the job it should.',
    introducedIn: 29,
    reviewPool: [
      proof('hp-r1', 'homophone-proofreading', 'Their going too the park with there friends.', [
        ['Their', "They're"], ['too', 'to'], ['there', 'their'],
      ]),
      proof('hp-r2', 'homophone-proofreading', 'I no you can here me from over their.', [
        ['no', 'know'], ['here', 'hear'], ['their', 'there'],
      ]),
      proof('hp-r3', 'homophone-proofreading', 'Its to cold to swim, and the water is to deep.', [
        ['Its', "It's"], ['to', 'too'],
      ]),
      mistake('hp-r4', 'homophone-proofreading', 'We one the game by to points.', 'one', 'won'),
      mistake('hp-r5', 'homophone-proofreading', 'Your bike is over their.', 'their', 'there'),
      mistake('hp-r6', 'homophone-proofreading', 'She new the answer already.', 'new', 'knew'),
      cloze('hp-r7', 'homophone-proofreading', 'We need ___ for the cake.', 'flour', { difficulty: 3 }),
      cloze('hp-r8', 'homophone-proofreading', 'She picked a yellow ___.', 'flower', { difficulty: 3 }),
      dictate('hp-r9', 'homophone-proofreading', 'They knew their new bikes were over there.', { difficulty: 3 }),
      mistake('hp-r10', 'homophone-proofreading', 'The wind blue the door shut.', 'blue', 'blew'),
    ],
  },
  {
    id: 'contractions',
    label: 'Contractions',
    patternReminder:
      'The apostrophe goes exactly where the missing letters were — not in the gap between the two words.',
    introducedIn: 30,
    reviewPool: [
      build('cn-r1', 'contractions', ['could', 'not'], "couldn't"),
      build('cn-r2', 'contractions', ['do', 'not'], "don't"),
      build('cn-r3', 'contractions', ['I', 'will'], "I'll"),
      build('cn-r4', 'contractions', ['they', 'are'], "they're"),
      build('cn-r5', 'contractions', ['is', 'not'], "isn't"),
      build('cn-r6', 'contractions', ['we', 'are'], "we're"),
      build('cn-r7', 'contractions', ['can', 'not'], "can't"),
      build('cn-r8', 'contractions', ['have', 'not'], "haven't"),
      aud('cn-r9', 'contractions', "didn't", { withSentence: false }),
      aud('cn-r10', 'contractions', "wouldn't"),
      cloze('cn-r11', 'contractions', 'I ___ find my shoes anywhere.', "couldn't", { difficulty: 2 }),
      mistake('cn-r12', 'contractions', 'We could\'nt hear the announcement.', "could'nt", "couldn't", {
        difficulty: 2,
      }),
    ],
  },
  {
    id: 'schwa',
    label: 'The lazy vowel',
    patternReminder:
      'That weak "uh" in the middle can be almost any vowel, so listening will not tell you. Say the word slowly and deliberately, or think of a related word where the vowel is clear.',
    introducedIn: 31,
    reviewPool: [
      aud('sw-r1', 'schwa', 'problem'),
      aud('sw-r2', 'schwa', 'animal'),
      aud('sw-r3', 'schwa', 'support'),
      aud('sw-r4', 'schwa', 'different'),
      aud('sw-r5', 'schwa', 'general'),
      aud('sw-r6', 'schwa', 'memory'),
      letters('sw-r7', 'schwa', 'about'),
      letters('sw-r8', 'schwa', 'garden'),
      letters('sw-r9', 'schwa', 'parent'),
      aud('sw-r10', 'schwa', 'camera', { difficulty: 2 }),
      aud('sw-r11', 'schwa', 'separate', { difficulty: 3 }),
      aud('sw-r12', 'schwa', 'vegetable', { difficulty: 3 }),
    ],
  },
  {
    id: 'two-way-splitting',
    label: 'Splitting a word two ways',
    patternReminder:
      'Split a hard word twice: once into beats you can say, and once into meaning parts you recognise. Both give you clues.',
    introducedIn: 32,
    reviewPool: [
      syl('tw-r1', 'two-way-splitting', 'interesting', { difficulty: 2 }),
      syl('tw-r2', 'two-way-splitting', 'comfortable', { difficulty: 3 }),
      syl('tw-r3', 'two-way-splitting', 'disappointment', { difficulty: 3 }),
      syl('tw-r4', 'two-way-splitting', 'independent', { difficulty: 3 }),
      build('tw-r5', 'two-way-splitting', ['un', 'help', 'ful', 'ness'], 'unhelpfulness'),
      build('tw-r6', 'two-way-splitting', ['dis', 'appoint', 'ment'], 'disappointment'),
      build('tw-r7', 'two-way-splitting', ['un', 'fortunate', 'ly'], 'unfortunately'),
      aud('tw-r8', 'two-way-splitting', 'unbelievable', { difficulty: 3 }),
      aud('tw-r9', 'two-way-splitting', 'extraordinary', { difficulty: 3 }),
      aud('tw-r10', 'two-way-splitting', 'unfortunately', { difficulty: 3 }),
    ],
  },
  {
    id: 'soft-c-g',
    label: 'Soft c and soft g',
    patternReminder:
      'Before e, i or y, "c" usually says /s/ and "g" usually says /j/. Before a, o or u they go back to their hard sounds.',
    alternatives: ['c', 's', 'g', 'j'],
    maskFrom: 'firstPart',
    introducedIn: 33,
    reviewPool: [
      aud('sc-r1', 'soft-c-g', 'circle'),
      aud('sc-r2', 'soft-c-g', 'cent'),
      aud('sc-r3', 'soft-c-g', 'circus'),
      aud('sc-r4', 'soft-c-g', 'gentle'),
      aud('sc-r5', 'soft-c-g', 'ginger'),
      aud('sc-r6', 'soft-c-g', 'gem'),
      sort('sc-r7', 'soft-c-g', {
        'c says /s/': ['city', 'cycle', 'cent'],
        'c says /k/': ['cat', 'cup', 'cot'],
      }),
      sort('sc-r8', 'soft-c-g', {
        'g says /j/': ['giant', 'gym', 'gem'],
        'g says /g/': ['gate', 'goat', 'gum'],
      }),
      cloze('sc-r9', 'soft-c-g', 'We live near the middle of the ___.', 'city', { difficulty: 2 }),
      aud('sc-r10', 'soft-c-g', 'giraffe', { difficulty: 2 }),
      aud('sc-r11', 'soft-c-g', 'celery', { difficulty: 2 }),
      aud('sc-r12', 'soft-c-g', 'germ'),
    ],
  },
  {
    id: 'tion-ending',
    label: 'The /shun/ ending',
    patternReminder:
      'That "shun" sound at the end of a word is nearly always written "tion". Find the base word first — collect becomes collection.',
    alternatives: ['tion', 'shun', 'sion'],
    maskFrom: 'lastPart',
    introducedIn: 34,
    reviewPool: [
      aud('ti-r1', 'tion-ending', 'station'),
      aud('ti-r2', 'tion-ending', 'question'),
      aud('ti-r3', 'tion-ending', 'attention'),
      aud('ti-r4', 'tion-ending', 'direction'),
      aud('ti-r5', 'tion-ending', 'fraction'),
      aud('ti-r6', 'tion-ending', 'section'),
      build('ti-r7', 'tion-ending', ['act', 'ion'], 'action'),
      build('ti-r8', 'tion-ending', ['collect', 'ion'], 'collection'),
      build('ti-r9', 'tion-ending', ['invent', 'ion'], 'invention'),
      cloze('ti-r10', 'tion-ending', 'We waited at the train ___.', 'station', { difficulty: 2 }),
      aud('ti-r11', 'tion-ending', 'celebration', { difficulty: 3 }),
      aud('ti-r12', 'tion-ending', 'imagination', { difficulty: 3 }),
    ],
  },
  {
    id: 'word-roots',
    label: 'Ancient word pieces',
    patternReminder:
      'Some word pieces come from Greek and Latin and carry meaning wherever they go: "tele" means far, "photo" means light, "micro" means small.',
    maskFrom: 'firstPart',
    introducedIn: 35,
    reviewPool: [
      aud('wr-r1', 'word-roots', 'telescope'),
      aud('wr-r2', 'word-roots', 'telephone'),
      aud('wr-r3', 'word-roots', 'photograph'),
      aud('wr-r4', 'word-roots', 'microscope'),
      aud('wr-r5', 'word-roots', 'microphone'),
      aud('wr-r6', 'word-roots', 'autograph'),
      build('wr-r7', 'word-roots', ['geo', 'graphy'], 'geography'),
      build('wr-r8', 'word-roots', ['bi', 'cycle'], 'bicycle'),
      build('wr-r9', 'word-roots', ['trans', 'port'], 'transport'),
      cloze('wr-r10', 'word-roots', 'We looked at the stars through a ___.', 'telescope', { difficulty: 2 }),
      aud('wr-r11', 'word-roots', 'aquarium', { difficulty: 3 }),
      aud('wr-r12', 'word-roots', 'television', { difficulty: 2 }),
    ],
  },
  {
    id: 'australian-spelling',
    label: 'Australian spellings',
    patternReminder:
      'Australian English keeps the u in "our" words and puts the r before the e in "tre" words. Verbs usually end in "ise", not "ize".',
    alternatives: ['our', 'or', 're', 'er', 'ise', 'ize'],
    maskFrom: 'lastPart',
    introducedIn: 36,
    reviewPool: [
      aud('au-r1', 'australian-spelling', 'harbour'),
      aud('au-r2', 'australian-spelling', 'neighbour'),
      aud('au-r3', 'australian-spelling', 'flavour'),
      aud('au-r4', 'australian-spelling', 'theatre'),
      aud('au-r5', 'australian-spelling', 'litre'),
      aud('au-r6', 'australian-spelling', 'honour'),
      cloze('au-r7', 'australian-spelling', 'My ___ is dark green.', 'colour'),
      cloze('au-r8', 'australian-spelling', 'The pool is fifty ___ long.', 'metres', { difficulty: 2 }),
      mistake('au-r9', 'australian-spelling', 'What is your favorite color?', 'favorite', 'favourite'),
      aud('au-r10', 'australian-spelling', 'realise', { difficulty: 2 }),
      aud('au-r11', 'australian-spelling', 'recognise', { difficulty: 3 }),
      aud('au-r12', 'australian-spelling', 'travelled', { difficulty: 2 }),
    ],
  },
  {
    id: 'proofreading',
    label: 'Proofreading your own writing',
    patternReminder:
      'Read it back one word at a time. Anything you are not sure of, split it and check the pattern you know.',
    introducedIn: 37,
    reviewPool: [
      proof('pr-r1', 'proofreading', 'We were runing to the shop when it started raning.', [
        ['runing', 'running'], ['raning', 'raining'],
      ]),
      proof('pr-r2', 'proofreading', 'The babys were sleeping quietley in there cots.', [
        ['babys', 'babies'], ['quietley', 'quietly'], ['there', 'their'],
      ]),
      proof('pr-r3', 'proofreading', 'My favorite color is the brightest yellow.', [
        ['favorite', 'favourite'], ['color', 'colour'],
      ]),
      mistake('pr-r4', 'proofreading', 'She was very carefull with the glass.', 'carefull', 'careful'),
      mistake('pr-r5', 'proofreading', 'The bridg was closed all morning.', 'bridg', 'bridge'),
      mistake('pr-r6', 'proofreading', 'He was the tallist boy in the class.', 'tallist', 'tallest'),
      proof('pr-r7', 'proofreading', 'I couldnt reach the sheff, so I climed on a chair.', [
        ['couldnt', "couldn't"], ['sheff', 'shelf'], ['climed', 'climbed'],
      ], { difficulty: 3 }),
    ],
  },
  {
    id: 'sentence-dictation',
    label: 'Writing a whole sentence',
    patternReminder:
      'Hold the sentence in your head, then write it one word at a time. For any word you are unsure of, say it, split it and find its base word.',
    introducedIn: 38,
    reviewPool: [
      dictate('sd-r1', 'sentence-dictation', 'The children were playing happily in the garden.', { difficulty: 2 }),
      dictate('sd-r2', 'sentence-dictation', 'My neighbour painted her fence a bright colour.', { difficulty: 3 }),
      dictate('sd-r3', 'sentence-dictation', 'We walked across the bridge to the station.', { difficulty: 2 }),
      dictate('sd-r4', 'sentence-dictation', 'Unfortunately the weather changed before lunch.', { difficulty: 3 }),
      dictate('sd-r5', 'sentence-dictation', 'They knew their answers were completely different.', { difficulty: 3 }),
      dictate('sd-r6', 'sentence-dictation', 'The giant telescope showed us the whole sky.', { difficulty: 3 }),
      dictate('sd-r7', 'sentence-dictation', 'She apologised because she had misplaced the keys.', { difficulty: 3 }),
    ],
  },
  {
    id: 'spellcheck-limits',
    label: 'When spellcheck cannot help',
    patternReminder:
      'Every word here exists, so nothing is underlined in red. Only the meaning tells you which one belongs.',
    introducedIn: 39,
    reviewPool: [
      mistake('sk-r1', 'spellcheck-limits', 'Their going to school early.', 'Their', "They're"),
      mistake('sk-r2', 'spellcheck-limits', 'I have two much homework.', 'two', 'too'),
      mistake('sk-r3', 'spellcheck-limits', 'Can you here the music?', 'here', 'hear'),
      mistake('sk-r4', 'spellcheck-limits', 'The dog hurt it\'s paw.', "it's", 'its'),
      mistake('sk-r5', 'spellcheck-limits', 'She new the answer straight away.', 'new', 'knew'),
      mistake('sk-r6', 'spellcheck-limits', 'We one the match on Saturday.', 'one', 'won'),
      proof('sk-r7', 'spellcheck-limits', 'Your write about there new bike.', [
        ['Your', "You're"], ['write', 'right'], ['there', 'their'],
      ], { difficulty: 3 }),
      proof('sk-r8', 'spellcheck-limits', 'Its to late to by any flours.', [
        ['Its', "It's"], ['to', 'too'], ['by', 'buy'], ['flours', 'flowers'],
      ], { difficulty: 3 }),
    ],
  },
  {
    id: 'mixed-mastery',
    label: 'Everything at once',
    patternReminder:
      'Nobody is going to tell you which pattern this is. Use all five clues: sounds, syllables, spelling patterns, word parts and meaning.',
    introducedIn: 40,
    reviewPool: [
      aud('mm-r1', 'mixed-mastery', 'celebration', { difficulty: 3 }),
      aud('mm-r2', 'mixed-mastery', 'neighbour', { difficulty: 3 }),
      aud('mm-r3', 'mixed-mastery', 'disappointment', { difficulty: 3 }),
      syl('mm-r4', 'mixed-mastery', 'extraordinary', { difficulty: 3 }),
      build('mm-r5', 'mixed-mastery', ['un', 'believe', 'able'], 'unbelievable', { difficulty: 3 }),
      dictate('mm-r6', 'mixed-mastery', 'Their neighbour was completely unhelpful.', { difficulty: 3 }),
      dictate('mm-r7', 'mixed-mastery', "It's too late to catch the earlier train.", { difficulty: 3 }),
      aud('mm-r8', 'mixed-mastery', 'imagination', { difficulty: 3 }),
    ],
  },
]

export const CONCEPTS: ReadonlyMap<ConceptId, Concept> = new Map(
  CONCEPT_LIST.map((concept) => [concept.id, concept]),
)

export function conceptLabel(id: ConceptId): string {
  return CONCEPTS.get(id)?.label ?? id
}
