/**
 * Level 2: the sky-ship.
 *
 * A thousand years on, the same quest in a different shape. The tile letters
 * mean exactly what they mean in the land — 'T' is the solid border, 'R' a
 * solid block, ',' something a tool clears, '~' something only the crossing
 * item gets you over — and the setting decides how each is drawn: hull panels
 * and deck plating on the ship, spires and crater dust out on the rocks.
 *
 * The map is laid out differently on purpose. The land is a long road north
 * from a village with dungeons at the ends; the ship is a block of decks he
 * works his way around, with the four rocks reached through airlocks off the
 * middle of it. Same ideas, different walk.
 */
import type { Screen } from './screens'

const SHIP = { level: 2, setting: 'ship' } as const
const ROCK = { level: 2, setting: 'rock' } as const
const AIRLOCK = { level: 2, setting: 'airlock' } as const

/**
 * An airlock: the corridor between the ship and a rock. No robots, one
 * locker, and the outer door that ends him if he forgets the suit.
 */
function airlock(
  id: string,
  name: string,
  ship: { to: string; spawnCol: number; spawnRow: number },
  rock: { to: string; spawnCol: number; spawnRow: number },
): Screen {
  return {
    id,
    name,
    region: 'Airlocks',
    ...AIRLOCK,
    // A tall chamber: the window onto the rock at the top, with the outer
    // hatch under it, and the way back to the ship at the bottom.
    rows: [
      '#####~~~~~~#####',
      '#####~~~~~~#####',
      '#######C########',
      '#####......#####',
      '#####......#####',
      '#####......#####',
      '#####......#####',
      '#####......#####',
      '#####......#####',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    portals: [
      { col: 7, row: 10, to: ship.to, spawnCol: ship.spawnCol, spawnRow: ship.spawnRow },
      { col: 7, row: 2, to: rock.to, spawnCol: rock.spawnCol, spawnRow: rock.spawnRow, needsSuit: true },
    ],
    props: [
      // The suit stands ready by the wall; walking into it puts it on.
      { sprite: 'spacesuit', col: 9, row: 4, locker: true },
      { sprite: 'canister', col: 5, row: 7, solid: true },
      {
        sprite: 'droid',
        col: 6,
        row: 5,
        talk: 'Suit up before the outer door. Walk into the suit to put it on. Out there, there is no air.',
      },
    ],
  }
}

export const AUTHORED_FUTURE: Screen[] = [
  // ------------------------------------------------------------- the bridge
  {
    id: 'ship-bridge',
    name: 'The Bridge',
    region: 'Bridge',
    ...SHIP,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T.RRRR....RRRR.T',
      'T.R..........R.T',
      'T..............T',
      '......SSSS......',
      'T....SSSSSS.....',
      'T....SSSSSS....T',
      'T.....SSSS.....T',
      'T..............T',
      'T.RR........RR.T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { left: 'ship-medbay', right: 'ship-corridor-1', down: 'ship-cargo-1' },
    props: [
      // The ship's stores: bump the console and the shop opens. It stands in
      // the rock alcove at the top so nothing has to walk round it.
      { sprite: 'terminal', col: 6, row: 1, terminal: 'village' },
      {
        sprite: 'droid',
        col: 11,
        row: 7,
        talk:
          'You are awake! The robots have taken the ship. Walk into the ' +
          'console up there to buy gear. And mind the airlocks — no suit, no air.',
      },
    ],
    pickup: {
      id: 'bridge-saber',
      col: 12,
      row: 3,
      item: 'woodenSword',
      message:
        'A training saber, dropped by a guard who did not get away. Its blade ' +
        'flickers on when you pick it up. Swing it with Z or Space.',
    },
  },
  {
    id: 'ship-medbay',
    name: 'The Medbay',
    region: 'Bridge',
    ...SHIP,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..RR......RR..T',
      'T..............T',
      'T....,....,....T',
      'T..............T',
      'T...............',
      'T..............T',
      'T....,....,....T',
      'T..............T',
      'T..RR......RR..T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { right: 'ship-bridge', down: 'ship-vault' },
    // The cyborg bay: his companion is chosen at a console, not in a cave.
    props: [
      { sprite: 'terminal', col: 7, row: 1, terminal: 'pets' },
      {
        sprite: 'droid',
        col: 3,
        row: 6,
        talk: 'The cyborg bay console is up there. Six of them, all waiting for someone to walk with.',
      },
    ],
    spawns: [{ kind: 'shooter', col: 11, row: 6 }],
  },
  {
    id: 'ship-observatory',
    name: 'The Observatory',
    region: 'Bridge',
    ...SHIP,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T~~~~~~~~~~~~~~T',
      'T~~~~~~~~~~~~~~T',
      'T~~~~~~~~~~~~~~T',
      'T..............T',
      'T....,....,....T',
      'T..............T',
      'T..............T',
      'T....X.........T',
      'T..............T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { down: 'ship-corridor-1' },
    gates: [{ gateId: 'ship-obs-chest', col: 11, row: 7 }],
    // A cracked bulkhead in the corner. Behind it, the schematic.
    portals: [{ col: 5, row: 8, to: 'ship-schematic-locker', spawnCol: 7, spawnRow: 8 }],
    spawns: [
      { kind: 'flyer', col: 4, row: 6 },
      { kind: 'shooter', col: 10, row: 6 },
    ],
  },

  // -------------------------------------------------------------- the decks
  {
    id: 'ship-corridor-1',
    name: 'The Main Corridor',
    region: 'Decks',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'TTTTTTT..TTTTTTT',
      'TTTTTTT==TTTTTTT',
      'T......,,......T',
      '..RR........RR..',
      '..RR........RR..',
      '................',
      'T....,....,....T',
      'T..............T',
      'T..............T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { left: 'ship-bridge', right: 'ship-corridor-2', up: 'ship-observatory', down: 'ship-cargo-2' },
    gates: [
      { gateId: 'ship-obs-seal', col: 7, row: 2, guards: 'up', opens: [{ col: 7, row: 2 }, { col: 8, row: 2 }] },
    ],
    spawns: [
      { kind: 'shooter', col: 5, row: 8 },
      { kind: 'chaser', col: 10, row: 8 },
    ],
  },
  {
    id: 'ship-corridor-2',
    name: 'The Long Deck',
    region: 'Decks',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'T......,,......T',
      'T..RR......RR..T',
      'T............TTT',
      '.............=..',
      'T............TTT',
      'T..RR......RR..T',
      'T.....,,,......T',
      'T..............T',
      'T..............T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { left: 'ship-corridor-1', up: 'ship-mess', right: 'ship-lab-1', down: 'ship-engine-1' },
    gates: [
      { gateId: 'ship-lab-seal', col: 13, row: 4, guards: 'right', opens: [{ col: 13, row: 4 }] },
    ],
    // Airlock one is off this deck, in the wall by the far crates.
    portals: [{ col: 11, row: 9, to: 'airlock-1', spawnCol: 7, spawnRow: 8 }],
    props: [
      {
        sprite: 'droid',
        col: 4,
        row: 8,
        talk: 'That hatch leads to Airlock One. The first of the rocks is out there, and something big with it.',
      },
    ],
    spawns: [
      { kind: 'chaser', col: 5, row: 4 },
      { kind: 'flyer', col: 11, row: 3 },
    ],
  },
  {
    id: 'ship-mess',
    name: 'The Mess Hall',
    region: 'Decks',
    ...SHIP,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T.RR.RR.RR.RR..T',
      'T.RR.RR.RR.RR..T',
      'T..............T',
      'T..............T',
      'T.RR.RR.RR.RR..T',
      'T.RR.RR.RR.RR..T',
      'T.......p......T',
      'T..............T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { down: 'ship-corridor-2' },
    gates: [{ gateId: 'ship-mess-guard', col: 13, row: 4 }],
    // A sealed panel among the tables, with something glinting behind it. The
    // first of the two serums, and the screwdriver is the way to it.
    pickup: {
      id: 'mess-serum',
      col: 8,
      row: 8,
      item: 'potion',
      message:
        'The panel comes off and a vial rolls out, cold and faintly humming. ' +
        'You drink it. The lights stop finding you.',
    },
    spawns: [
      { kind: 'shooter', col: 4, row: 4 },
      { kind: 'flyer', col: 10, row: 5 },
    ],
  },

  // ------------------------------------------------------------- the cargo
  {
    id: 'ship-cargo-1',
    name: 'Cargo Bay One',
    region: 'Cargo',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'T..............T',
      'T.RRR......RRR.T',
      'T.RRR......RRR.T',
      'T............TTT',
      '.............=..',
      'T............TTT',
      'T.RR...,....RR.T',
      'TTTTTTT==TTTTTTT',
      'T......,,......T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { up: 'ship-bridge', left: 'ship-vault', right: 'ship-cargo-2', down: 'ship-hangar' },
    gates: [
      { gateId: 'ship-cargo-seal', col: 13, row: 5, guards: 'right', opens: [{ col: 13, row: 5 }] },
      { gateId: 'ship-hangar-seal', col: 7, row: 8, guards: 'down', opens: [{ col: 7, row: 8 }, { col: 8, row: 8 }] },
    ],
    props: [
      {
        sprite: 'droid',
        col: 12,
        row: 6,
        talk: 'The hangar is below. The launch pad still works, if you have something to launch.',
      },
    ],
    spawns: [
      { kind: 'chaser', col: 7, row: 4 },
      { kind: 'shooter', col: 4, row: 6 },
    ],
  },
  {
    id: 'ship-vault',
    name: 'The Vault',
    region: 'Cargo',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'T......,,......T',
      'T..............T',
      'T....RRRRRR....T',
      'T....R....R....T',
      'T....R....R.....',
      'T....RR..RR....T',
      'T..............T',
      'T.X............T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: { up: 'ship-medbay', right: 'ship-cargo-1' },
    gates: [{ gateId: 'ship-vault-chest', col: 7, row: 4 }],
    // The black-market terminal, behind a cracked bulkhead. The graveyard's
    // hidden trader, a thousand years on.
    portals: [{ col: 2, row: 8, to: 'ship-black-market', spawnCol: 7, spawnRow: 8 }],
    spawns: [
      { kind: 'flyer', col: 4, row: 2 },
      { kind: 'flyer', col: 11, row: 8 },
    ],
  },
  {
    id: 'ship-cargo-2',
    name: 'Cargo Bay Two',
    region: 'Cargo',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'T..............T',
      'T..RR......RR..T',
      'T..............T',
      'T..............T',
      '................',
      'T..............T',
      'T....,,,,......T',
      'T..RR......RR..T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: { up: 'ship-corridor-1', left: 'ship-cargo-1', right: 'ship-engine-1' },
    gates: [
      { gateId: 'ship-cargo-guard', col: 9, row: 3 },
      { gateId: 'ship-cargo-chest', col: 4, row: 6 },
    ],
    // Airlock two, behind the loose cabling at the bottom: the screwdriver
    // finds it, the way the candle finds the forest grotto.
    portals: [{ col: 6, row: 7, to: 'airlock-2', spawnCol: 7, spawnRow: 8 }],
    spawns: [
      { kind: 'chaser', col: 11, row: 4 },
      { kind: 'shooter', col: 4, row: 4 },
    ],
  },
  {
    id: 'ship-hangar',
    name: 'The Hangar',
    region: 'Cargo',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'T......,,......T',
      'T..............T',
      'T....=SSS~~~~~~~',
      'T....=SSS~~~~~~~',
      'T....=SSSS~~~~~~',
      'T....=SSS~~~~~~~',
      'T....=SSS~~~~~~~',
      'T..............T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: { up: 'ship-cargo-1' },
    gates: [
      {
        gateId: 'ship-launch-passage',
        col: 5,
        row: 5,
        opens: [
          { col: 5, row: 3 },
          { col: 5, row: 4 },
          { col: 5, row: 5 },
          { col: 5, row: 6 },
          { col: 5, row: 7 },
        ],
      },
    ],
    // The launch pad. The rocket carries him across the void to the outpost
    // and burns out doing it — the island crossing, in space.
    portals: [
      {
        col: 9,
        row: 5,
        to: 'outpost-deck',
        spawnCol: 5,
        spawnRow: 5,
        requires: 'wings',
        consumes: true,
        refusal: 'Open space, and a long way across it. Nothing walks over that.',
      },
    ],
    props: [
      {
        sprite: 'droid',
        col: 3,
        row: 9,
        talk: 'There is an outpost out there past the bay doors. Nobody has been across since the robots came.',
      },
    ],
    spawns: [{ kind: 'flyer', col: 3, row: 2 }],
  },

  // ---------------------------------------------------------- engineering
  {
    id: 'ship-engine-1',
    name: 'Engineering',
    region: 'Engineering',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'T......,,......T',
      'T.RRRR....RRRR.T',
      'T..............T',
      '...............T',
      'T....,....,....T',
      'T..............T',
      'T.RRRR....RRRR.T',
      'TTTTTTT==TTTTTTT',
      'T......,,......T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { up: 'ship-corridor-2', left: 'ship-cargo-2', down: 'ship-engine-2' },
    gates: [
      { gateId: 'ship-engine-seal', col: 7, row: 8, guards: 'down', opens: [{ col: 7, row: 8 }, { col: 8, row: 8 }] },
    ],
    // The forge console: the smithy, as a computer.
    props: [
      { sprite: 'terminal', col: 7, row: 2, terminal: 'smith' },
      {
        sprite: 'droid',
        col: 12,
        row: 6,
        talk: 'The forge console prints weapons, for rupees and a steady mind. The Arc Staff is the last thing it makes.',
      },
    ],
    spawns: [
      { kind: 'shooter', col: 4, row: 5 },
      { kind: 'chaser', col: 11, row: 5 },
    ],
  },
  {
    id: 'ship-engine-2',
    name: 'The Coolant Deck',
    region: 'Engineering',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'T..............T',
      'T.~~~~~..~~~~~.T',
      'T.~~~~~..~~~~~.T',
      'T......,,....TTT',
      'T............=..',
      'T.~~~~~..~~~~TTT',
      'T.~~~~~..~~~~~.T',
      'T..............T',
      'T..............T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { up: 'ship-engine-1', right: 'ship-reactor', down: 'ship-lower-deck' },
    gates: [
      { gateId: 'ship-reactor-seal', col: 13, row: 5, guards: 'right', opens: [{ col: 13, row: 5 }] },
    ],
    // Airlock three, off the coolant deck.
    portals: [{ col: 3, row: 9, to: 'airlock-3', spawnCol: 7, spawnRow: 8 }],
    spawns: [
      { kind: 'flyer', col: 4, row: 5 },
      { kind: 'flyer', col: 11, row: 5 },
    ],
  },
  {
    id: 'ship-reactor',
    name: 'The Reactor',
    region: 'Engineering',
    ...SHIP,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T....*....*....T',
      'T..............T',
      'T....RRRRRR....T',
      'T....R.DD.R....T',
      '.....RR..RR....T',
      'T......,,......T',
      'T..............T',
      'T....,....,....T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: { left: 'ship-engine-2' },
    // The reactor keeper guards the way down into the fourth rock: the shrine
    // steps, made of steel.
    gates: [{ gateId: 'ship-reactor-keeper', col: 7, row: 4, opens: [{ col: 7, row: 4 }, { col: 8, row: 4 }] }],
    portals: [{ col: 7, row: 4, to: 'airlock-4', spawnCol: 7, spawnRow: 8 }],
    props: [
      {
        sprite: 'droid',
        col: 4,
        row: 7,
        talk: 'The keeper droid guards the reactor hatch. Answer it and Airlock Four opens. The biggest of them is out there.',
      },
    ],
    spawns: [{ kind: 'caster', col: 11, row: 8 }],
  },
  {
    id: 'ship-lower-deck',
    name: 'The Lower Deck',
    region: 'Engineering',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'T......,,......T',
      'T..RR......RR..T',
      'T..............T',
      'T..............T',
      'T..............T',
      'T..RR......RR..T',
      'T..............T',
      'T..........X...T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: { up: 'ship-engine-2' },
    gates: [
      { gateId: 'ship-lower-chest', col: 4, row: 4 },
      { gateId: 'ship-lower-guard', col: 7, row: 3 },
    ],
    // The smugglers' hold, behind a cracked bulkhead: the bomb shop of the ship.
    portals: [{ col: 11, row: 8, to: 'ship-smugglers-hold', spawnCol: 7, spawnRow: 8 }],
    spawns: [
      { kind: 'caster', col: 4, row: 8 },
      { kind: 'chaser', col: 11, row: 4 },
    ],
  },

  // --------------------------------------------------------------- the labs
  {
    id: 'ship-lab-1',
    name: 'Laboratory One',
    region: 'Labs',
    ...SHIP,
    rows: [
      'TTTTTTT..TTTTTTT',
      'T......,,......T',
      'TTTTTTT==TTTTTTT',
      'T.RR........RR.T',
      '...............T',
      'T..............T',
      'T.RR........RR.T',
      'T.....,........T',
      'T..............T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: { left: 'ship-corridor-2', up: 'ship-lab-2' },
    gates: [
      { gateId: 'ship-lab-seal-2', col: 7, row: 2, guards: 'up', opens: [{ col: 7, row: 2 }, { col: 8, row: 2 }] },
      { gateId: 'ship-lab-chest', col: 12, row: 8 },
    ],
    spawns: [
      { kind: 'caster', col: 5, row: 5 },
      { kind: 'chaser', col: 10, row: 5 },
    ],
  },
  {
    id: 'ship-lab-2',
    name: 'Laboratory Two',
    region: 'Labs',
    ...SHIP,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..RR......RR..T',
      'T............TTT',
      'T............=..',
      'T............TTT',
      'T....,....,....T',
      'T..............T',
      'T..RR......RR..T',
      'T...........p..T',
      'T..............T',
      'TTTTTTT..TTTTTTT',
    ],
    exits: { down: 'ship-lab-1', right: 'ship-lab-3' },
    gates: [
      { gateId: 'ship-lab-seal-3', col: 13, row: 3, guards: 'right', opens: [{ col: 13, row: 3 }] },
    ],
    // The second serum, at the far end of the labs — three barriers from the
    // first one, in another region, behind a panel nobody would look at twice.
    pickup: {
      id: 'lab-serum',
      col: 12,
      row: 8,
      item: 'potion',
      message:
        'Behind the panel, a vial in a cradle of wires, still cold. You drink it, ' +
        'and even the cameras lose you.',
    },
    spawns: [
      { kind: 'caster', col: 4, row: 3 },
      { kind: 'flyer', col: 11, row: 6 },
    ],
  },
  {
    id: 'ship-lab-3',
    name: 'The Specimen Room',
    region: 'Labs',
    ...SHIP,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..*..*..*..*..T',
      'T..............T',
      '...*..*..*..*..T',
      'T..............T',
      'T..............T',
      'T..*..*..*..*..T',
      'T..............T',
      'T.....,........T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: { left: 'ship-lab-2' },
    gates: [
      { gateId: 'ship-lab-guard', col: 10, row: 5 },
      { gateId: 'ship-specimen-chest', col: 13, row: 8 },
    ],
    // The maintenance bay: a hidden room under the cabling, with a chest.
    portals: [{ col: 6, row: 8, to: 'ship-maintenance-bay', spawnCol: 7, spawnRow: 8 }],
    spawns: [
      { kind: 'caster', col: 7, row: 5 },
      { kind: 'chaser', col: 12, row: 7 },
    ],
  },

  // ---------------------------------------------------------- hidden rooms
  {
    id: 'ship-schematic-locker',
    name: 'The Chart Locker',
    region: 'Bridge',
    ...SHIP,
    rows: [
      '################',
      '#..............#',
      '#..............#',
      '#....######....#',
      '#....#....#....#',
      '#....#....#....#',
      '#....##..##....#',
      '#..............#',
      '#######..#######',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    pickup: {
      id: 'ship-schematic',
      col: 7,
      row: 4,
      item: 'map',
      message:
        'A schematic of the whole ship, folded into a locker nobody opened ' +
        'in a thousand years. Every deck is on it.',
    },
    props: [
      { sprite: 'droid', col: 4, row: 7, talk: 'You blew the bulkhead in for this? Good. Nobody else bothered.' },
    ],
    portals: [{ col: 7, row: 10, to: 'ship-observatory', spawnCol: 5, spawnRow: 7 }],
  },
  {
    id: 'ship-black-market',
    name: 'A Hidden Terminal',
    region: 'Cargo',
    ...SHIP,
    rows: [
      '################',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#######..#######',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    dark: true,
    portals: [{ col: 7, row: 10, to: 'ship-vault', spawnCol: 2, spawnRow: 9 }],
    props: [
      { sprite: 'terminal', col: 7, row: 3, terminal: 'secret' },
      {
        sprite: 'droid',
        col: 3,
        row: 6,
        talk: 'You found it. Few do. That terminal sells what the stores will not, and nobody up there knows.',
      },
    ],
    gates: [{ gateId: 'ship-circuit-ring', col: 7, row: 4 }],
  },
  {
    id: 'ship-smugglers-hold',
    name: "The Smugglers' Hold",
    region: 'Engineering',
    ...SHIP,
    rows: [
      '################',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#######..#######',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    dark: true,
    portals: [{ col: 7, row: 10, to: 'ship-lower-deck', spawnCol: 11, spawnRow: 9 }],
    props: [
      { sprite: 'terminal', col: 7, row: 3, terminal: 'secret' },
      {
        sprite: 'droid',
        col: 11,
        row: 6,
        talk: 'You blew the wall in, so you have earned a look. Charges and patches, nothing fancy.',
      },
    ],
    gates: [{ gateId: 'ship-smugglers', col: 7, row: 4 }],
  },
  {
    id: 'ship-maintenance-bay',
    name: 'The Maintenance Bay',
    region: 'Labs',
    ...SHIP,
    rows: [
      '################',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#######..#######',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    dark: true,
    props: [{ sprite: 'droid', col: 7, row: 3, talk: 'Not many find this bay. Take what you like.' }],
    gates: [{ gateId: 'ship-maintenance-chest', col: 5, row: 3 }],
    portals: [{ col: 7, row: 10, to: 'ship-lab-3', spawnCol: 6, spawnRow: 7 }],
  },

  // ------------------------------------------------------------ the outpost
  //
  // Across the void from the hangar. A rocket gets him there and burns out on
  // landing; the terminal below sells the one home, for a price.
  {
    id: 'outpost-deck',
    name: 'The Outpost',
    region: 'Outpost',
    ...SHIP,
    rows: [
      '~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~',
      '~~~~~SSSSSS~~~~~',
      '~~~~SSSSSSSS~~~~',
      '~~~SSSSCSSSSS~~~',
      '~~~SSSSSSSSSS~~~',
      '~~~~SSSSSSSS~~~~',
      '~~~~~SSSSSS~~~~~',
      '~~~~~~SSSS~~~~~~',
      '~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~',
    ],
    exits: {},
    pickup: {
      id: 'outpost-screwdriver',
      col: 7,
      row: 5,
      item: 'blueCandle',
      message:
        'A laser screwdriver, left on the landing pad. Someone else came this far. Press X to use it.',
    },
    portals: [
      { col: 7, row: 4, to: 'outpost-hold', spawnCol: 7, spawnRow: 8 },
      {
        col: 11,
        row: 5,
        to: 'ship-hangar',
        spawnCol: 6,
        spawnRow: 5,
        requires: 'wings',
        consumes: true,
        refusal: 'The ship is a long way off across the dark, and you have nothing to fly with.',
      },
    ],
  },
  {
    id: 'outpost-hold',
    name: "The Outpost's Hold",
    region: 'Outpost',
    ...SHIP,
    rows: [
      '################',
      '#..............#',
      '#..RR......RR..#',
      '#..............#',
      '#.......^......#',
      '#..............#',
      '#..RR......RR..#',
      '#..............#',
      '#..............#',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    dark: true,
    treasure: {
      id: 'outpost-hoard',
      col: 7,
      row: 1,
      rupees: 500,
      message: 'A strongbox, packed to the lid. Whoever left this here never came back for it.',
    },
    gates: [{ gateId: 'outpost-toll', col: 8, row: 4 }],
    portals: [
      { col: 7, row: 10, to: 'outpost-deck', spawnCol: 7, spawnRow: 5 },
      { col: 8, row: 4, to: 'outpost-deep', spawnCol: 7, spawnRow: 8, guardedBy: 'outpost-toll' },
    ],
    spawns: [{ kind: 'chaser', col: 4, row: 7 }],
  },
  {
    id: 'outpost-deep',
    name: 'The Stranded Pilot',
    region: 'Outpost',
    ...SHIP,
    rows: [
      '################',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#..............#',
      '#######..#######',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    portals: [{ col: 7, row: 10, to: 'outpost-hold', spawnCol: 8, spawnRow: 5 }],
    props: [
      { sprite: 'terminal', col: 7, row: 3, terminal: 'castaway' },
      {
        sprite: 'droid',
        col: 4,
        row: 6,
        talk: 'The pilot shrugs. "I did the same thing you did. Difference is, I started selling."',
      },
    ],
  },

  // ------------------------------------------------------------- airlocks
  airlock('airlock-1', 'Airlock One', { to: 'ship-corridor-2', spawnCol: 11, spawnRow: 8 }, { to: 'rock-1-landing', spawnCol: 13, spawnRow: 5 }),
  airlock('airlock-2', 'Airlock Two', { to: 'ship-cargo-2', spawnCol: 6, spawnRow: 6 }, { to: 'rock-2-landing', spawnCol: 13, spawnRow: 5 }),
  airlock('airlock-3', 'Airlock Three', { to: 'ship-engine-2', spawnCol: 3, spawnRow: 8 }, { to: 'rock-3-landing', spawnCol: 13, spawnRow: 5 }),
  airlock('airlock-4', 'Airlock Four', { to: 'ship-reactor', spawnCol: 7, spawnRow: 6 }, { to: 'rock-4-landing', spawnCol: 13, spawnRow: 5 }),

  // ------------------------------------------------- rock one: the Grey Rock
  //
  // Each rock is four places: the landing, a crater, a vein with a chest, and
  // the core where the guardian is. Shorter than a dungeon of the land, and
  // wider: the rooms open sideways rather than in a line.
  {
    id: 'rock-1-landing',
    name: 'The Grey Rock',
    region: 'Grey Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T..RR..........T',
      'T..............T',
      'T.....,....R...T',
      'T..C..........CT',
      'T..............T',
      'T..R...........T',
      'T..........RR..T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    gates: [{ gateId: 'rock-1-door-1', col: 3, row: 5 }],
    portals: [
      { col: 14, row: 5, to: 'airlock-1', spawnCol: 7, spawnRow: 3 },
      { col: 3, row: 5, to: 'rock-1-crater', spawnCol: 13, spawnRow: 5, guardedBy: 'rock-1-door-1' },
    ],
    spawns: [
      { kind: 'shooter', col: 7, row: 3 },
      { kind: 'chaser', col: 7, row: 8 },
    ],
  },
  {
    id: 'rock-1-crater',
    name: 'The Grey Crater',
    region: 'Grey Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T......C.......T',
      'T..............T',
      'T....~~~~~~....T',
      'T...~~~~~~~~...T',
      'T..C~~~~~~~~..CT',
      'T...~~~~~~~~...T',
      'T....~~~~~~....T',
      'T.....,,,......T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    gates: [
      { gateId: 'rock-1-door-2', col: 3, row: 5 },
      { gateId: 'rock-1-hatch', col: 7, row: 1 },
    ],
    portals: [
      { col: 14, row: 5, to: 'rock-1-landing', spawnCol: 3, spawnRow: 6 },
      { col: 7, row: 1, to: 'rock-1-vein', spawnCol: 7, spawnRow: 8 },
      { col: 3, row: 5, to: 'rock-1-core', spawnCol: 13, spawnRow: 5, guardedBy: 'rock-1-door-2' },
    ],
    spawns: [
      { kind: 'flyer', col: 3, row: 2 },
      { kind: 'flyer', col: 12, row: 8 },
    ],
  },
  {
    id: 'rock-1-vein',
    name: 'The Crystal Vein',
    region: 'Grey Rock',
    ...ROCK,
    rows: [
      '################',
      '#..............#',
      '#....######....#',
      '#....#....#....#',
      '#....#....#....#',
      '#....##..##....#',
      '#......==......#',
      '#......,,......#',
      '#..............#',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    dark: true,
    gates: [
      { gateId: 'rock-1-vein-door', col: 7, row: 6, opens: [{ col: 7, row: 6 }, { col: 8, row: 6 }] },
      { gateId: 'rock-1-chest', col: 7, row: 3 },
    ],
    portals: [{ col: 7, row: 10, to: 'rock-1-crater', spawnCol: 7, spawnRow: 2 }],
    spawns: [{ kind: 'chaser', col: 3, row: 8 }],
  },
  {
    id: 'rock-1-core',
    name: 'The Grey Core',
    region: 'Grey Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T..............T',
      'T..............T',
      'T..............T',
      'T.............CT',
      'T..............T',
      'T..............T',
      'T..............T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    portals: [{ col: 14, row: 5, to: 'rock-1-crater', spawnCol: 3, spawnRow: 6 }],
    spawns: [{ kind: 'boss1', col: 4, row: 4 }],
  },

  // ------------------------------------------------ rock two: the Red Rock
  {
    id: 'rock-2-landing',
    name: 'The Red Rock',
    region: 'Red Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T.RR.......RR..T',
      'T.RR.......RR..T',
      'T.....,........T',
      'T..C..........CT',
      'T..............T',
      'T.RR.......RR..T',
      'T.RR..X....RR..T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    gates: [{ gateId: 'rock-2-door-1', col: 3, row: 5 }],
    portals: [
      { col: 14, row: 5, to: 'airlock-2', spawnCol: 7, spawnRow: 3 },
      { col: 3, row: 5, to: 'rock-2-crater', spawnCol: 13, spawnRow: 5, guardedBy: 'rock-2-door-1' },
      // A cracked boulder, and a cache behind it. The Ember Vault's alcove.
      { col: 6, row: 8, to: 'rock-2-cache', spawnCol: 7, spawnRow: 8 },
    ],
    spawns: [
      { kind: 'caster', col: 7, row: 3 },
      { kind: 'shooter', col: 7, row: 7 },
    ],
  },
  {
    id: 'rock-2-cache',
    name: 'A Blasted Hollow',
    region: 'Red Rock',
    ...ROCK,
    rows: [
      '################',
      '#..............#',
      '#..............#',
      '#....######....#',
      '#....#....#....#',
      '#....#....#....#',
      '#....##..##....#',
      '#..............#',
      '#..............#',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    dark: true,
    gates: [{ gateId: 'rock-2-cache-chest', col: 7, row: 4 }],
    portals: [{ col: 7, row: 10, to: 'rock-2-landing', spawnCol: 6, spawnRow: 9 }],
    spawns: [{ kind: 'flyer', col: 3, row: 8 }],
  },
  {
    id: 'rock-2-crater',
    name: 'The Red Crater',
    region: 'Red Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T......C.......T',
      'T..............T',
      'T..RR......RR..T',
      'T..............T',
      'T..C..........CT',
      'T..............T',
      'T..RR......RR..T',
      'T.....,,,......T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    dark: true,
    gates: [
      { gateId: 'rock-2-door-2', col: 3, row: 5 },
      { gateId: 'rock-2-hatch', col: 7, row: 1 },
    ],
    portals: [
      { col: 14, row: 5, to: 'rock-2-landing', spawnCol: 3, spawnRow: 6 },
      { col: 7, row: 1, to: 'rock-2-vein', spawnCol: 7, spawnRow: 8 },
      { col: 3, row: 5, to: 'rock-2-core', spawnCol: 13, spawnRow: 5, guardedBy: 'rock-2-door-2' },
    ],
    spawns: [
      { kind: 'caster', col: 5, row: 5 },
      { kind: 'chaser', col: 10, row: 5 },
    ],
  },
  {
    id: 'rock-2-vein',
    name: 'The Red Vein',
    region: 'Red Rock',
    ...ROCK,
    rows: [
      '################',
      '#..............#',
      '#...########...#',
      '#...#......#...#',
      '#...#......#...#',
      '#...###..###...#',
      '#......==......#',
      '#......,,......#',
      '#..............#',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    gates: [
      { gateId: 'rock-2-vein-door', col: 7, row: 6, opens: [{ col: 7, row: 6 }, { col: 8, row: 6 }] },
      { gateId: 'rock-2-chest', col: 7, row: 3 },
    ],
    portals: [{ col: 7, row: 10, to: 'rock-2-crater', spawnCol: 7, spawnRow: 2 }],
    spawns: [{ kind: 'chaser', col: 3, row: 8 }],
  },
  {
    id: 'rock-2-core',
    name: 'The Red Core',
    region: 'Red Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T..............T',
      'T..............T',
      'T..............T',
      'T.............CT',
      'T..............T',
      'T..............T',
      'T..............T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    portals: [{ col: 14, row: 5, to: 'rock-2-crater', spawnCol: 3, spawnRow: 6 }],
    spawns: [{ kind: 'boss2', col: 4, row: 4 }],
  },

  // ---------------------------------------------- rock three: the Ice Rock
  {
    id: 'rock-3-landing',
    name: 'The Ice Rock',
    region: 'Ice Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T..~~~....~~~..T',
      'T..~~~....~~~..T',
      'T..............T',
      'T..C..........CT',
      'T......,,......T',
      'T..............T',
      'T..R........R..T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    gates: [{ gateId: 'rock-3-door-1', col: 3, row: 5 }],
    portals: [
      { col: 14, row: 5, to: 'airlock-3', spawnCol: 7, spawnRow: 3 },
      { col: 3, row: 5, to: 'rock-3-crater', spawnCol: 13, spawnRow: 5, guardedBy: 'rock-3-door-1' },
    ],
    spawns: [
      { kind: 'caster', col: 7, row: 4 },
      { kind: 'shooter', col: 11, row: 8 },
    ],
  },
  {
    id: 'rock-3-crater',
    name: 'The Ice Crater',
    region: 'Ice Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T......C.......T',
      'T.~~~~~..~~~~~.T',
      'T.~~~~~..~~~~~.T',
      'T..............T',
      'T..C..........CT',
      'T..............T',
      'T.~~~~~..~~~~~.T',
      'T.~~~~~,,~~~~~.T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    gates: [
      { gateId: 'rock-3-door-2', col: 3, row: 5 },
      { gateId: 'rock-3-hatch', col: 7, row: 1 },
    ],
    portals: [
      { col: 14, row: 5, to: 'rock-3-landing', spawnCol: 3, spawnRow: 6 },
      { col: 7, row: 1, to: 'rock-3-vein', spawnCol: 7, spawnRow: 8 },
      { col: 3, row: 5, to: 'rock-3-core', spawnCol: 13, spawnRow: 5, guardedBy: 'rock-3-door-2' },
    ],
    spawns: [
      { kind: 'caster', col: 5, row: 5 },
      { kind: 'caster', col: 10, row: 5 },
    ],
  },
  {
    id: 'rock-3-vein',
    name: 'The Ice Vein',
    region: 'Ice Rock',
    ...ROCK,
    rows: [
      '################',
      '#..............#',
      '#..##########..#',
      '#..#........#..#',
      '#..#........#..#',
      '#..####..####..#',
      '#......==......#',
      '#......,,......#',
      '#..............#',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    dark: true,
    gates: [
      { gateId: 'rock-3-vein-door', col: 7, row: 6, opens: [{ col: 7, row: 6 }, { col: 8, row: 6 }] },
      { gateId: 'rock-3-chest', col: 7, row: 3 },
    ],
    portals: [{ col: 7, row: 10, to: 'rock-3-crater', spawnCol: 7, spawnRow: 2 }],
    spawns: [{ kind: 'caster', col: 3, row: 8 }],
  },
  {
    id: 'rock-3-core',
    name: 'The Ice Core',
    region: 'Ice Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T..............T',
      'T..............T',
      'T..............T',
      'T.............CT',
      'T..............T',
      'T..............T',
      'T..............T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    portals: [{ col: 14, row: 5, to: 'rock-3-crater', spawnCol: 3, spawnRow: 6 }],
    spawns: [{ kind: 'boss3', col: 4, row: 4 }],
  },

  // --------------------------------------------- rock four: the Black Rock
  {
    id: 'rock-4-landing',
    name: 'The Black Rock',
    region: 'Black Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T..RRRR..RRRR..T',
      'T..R........R..T',
      'T..............T',
      'T..C..........CT',
      'T..............T',
      'T..R........R..T',
      'T..RRRR..RRRR..T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    gates: [{ gateId: 'rock-4-door-1', col: 3, row: 5 }],
    portals: [
      { col: 14, row: 5, to: 'airlock-4', spawnCol: 7, spawnRow: 3 },
      { col: 3, row: 5, to: 'rock-4-crater', spawnCol: 13, spawnRow: 5, guardedBy: 'rock-4-door-1' },
    ],
    spawns: [
      { kind: 'caster', col: 7, row: 4 },
      { kind: 'chaser', col: 7, row: 7 },
    ],
  },
  {
    id: 'rock-4-crater',
    name: 'The Black Crater',
    region: 'Black Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T......C.......T',
      'T.RRRR....RRRR.T',
      'T..............T',
      'T....RRRRRR....T',
      'T..C..........CT',
      'T....RRRRRR....T',
      'T..............T',
      'T.RRRR,,,,RRRR.T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    gates: [
      { gateId: 'rock-4-door-2', col: 3, row: 5 },
      { gateId: 'rock-4-hatch', col: 7, row: 1 },
    ],
    portals: [
      { col: 14, row: 5, to: 'rock-4-landing', spawnCol: 3, spawnRow: 6 },
      { col: 7, row: 1, to: 'rock-4-vein', spawnCol: 7, spawnRow: 8 },
      { col: 3, row: 5, to: 'rock-4-core', spawnCol: 13, spawnRow: 5, guardedBy: 'rock-4-door-2' },
    ],
    spawns: [
      { kind: 'caster', col: 3, row: 3 },
      { kind: 'flyer', col: 12, row: 7 },
      { kind: 'chaser', col: 7, row: 7 },
    ],
  },
  {
    id: 'rock-4-vein',
    name: 'The Black Vein',
    region: 'Black Rock',
    ...ROCK,
    rows: [
      '################',
      '#..............#',
      '#..##########..#',
      '#..#........#..#',
      '#..#........#..#',
      '#..####..####..#',
      '#......==......#',
      '#......,,......#',
      '#..............#',
      '#######..#######',
      '#######..#######',
    ],
    exits: {},
    dark: true,
    gates: [
      { gateId: 'rock-4-vein-door', col: 7, row: 6, opens: [{ col: 7, row: 6 }, { col: 8, row: 6 }] },
      { gateId: 'rock-4-chest', col: 7, row: 3 },
    ],
    portals: [{ col: 7, row: 10, to: 'rock-4-crater', spawnCol: 7, spawnRow: 2 }],
    spawns: [
      { kind: 'caster', col: 3, row: 7 },
      { kind: 'caster', col: 12, row: 7 },
    ],
  },
  {
    id: 'rock-4-core',
    name: 'The Black Core',
    region: 'Black Rock',
    ...ROCK,
    rows: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T..............T',
      'T..............T',
      'T..............T',
      'T.............CT',
      'T..............T',
      'T..............T',
      'T..............T',
      'T..............T',
      'TTTTTTTTTTTTTTTT',
    ],
    exits: {},
    portals: [{ col: 14, row: 5, to: 'rock-4-crater', spawnCol: 3, spawnRow: 6 }],
    spawns: [{ kind: 'boss4', col: 4, row: 4 }],
  },
]
